# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showpersondata_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_showpersondata(object):
    def setupUi(self, showpersondata):
        showpersondata.setObjectName("showpersondata")
        showpersondata.resize(400, 460)
        showpersondata.setMinimumSize(QtCore.QSize(400, 460))
        showpersondata.setMaximumSize(QtCore.QSize(15616, 2262))
        showpersondata.setSizeGripEnabled(True)
        self.pushButton = QtWidgets.QPushButton(showpersondata)
        self.pushButton.setGeometry(QtCore.QRect(270, 370, 93, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    border-width: 1px;\n"
"    background-color: white;\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: rgb(240,240,240);\n"
"    border-style: inset;\n"
"    }")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(showpersondata)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 231, 16))
        self.label_5.setObjectName("label_5")
        self.gridLayoutWidget = QtWidgets.QWidget(showpersondata)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 80, 331, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.location = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.location.setMinimumSize(QtCore.QSize(252, 17))
        self.location.setMaximumSize(QtCore.QSize(252, 17))
        self.location.setStyleSheet("background-color: transparent")
        self.location.setFrame(False)
        self.location.setReadOnly(True)
        self.location.setObjectName("location")
        self.gridLayout.addWidget(self.location, 3, 1, 1, 1)
        self.username = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.username.setMinimumSize(QtCore.QSize(252, 17))
        self.username.setMaximumSize(QtCore.QSize(252, 17))
        self.username.setStyleSheet("background-color: transparent")
        self.username.setFrame(False)
        self.username.setReadOnly(True)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(70, 20))
        self.label_4.setMaximumSize(QtCore.QSize(70, 20))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(70, 20))
        self.label_2.setMaximumSize(QtCore.QSize(70, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.sex = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.sex.setMinimumSize(QtCore.QSize(252, 17))
        self.sex.setMaximumSize(QtCore.QSize(252, 17))
        self.sex.setStyleSheet("background-color: transparent")
        self.sex.setFrame(False)
        self.sex.setReadOnly(True)
        self.sex.setObjectName("sex")
        self.gridLayout.addWidget(self.sex, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(70, 20))
        self.label.setMaximumSize(QtCore.QSize(70, 20))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.age = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.age.setMinimumSize(QtCore.QSize(252, 17))
        self.age.setMaximumSize(QtCore.QSize(252, 17))
        self.age.setStyleSheet("background-color: transparent")
        self.age.setFrame(False)
        self.age.setReadOnly(True)
        self.age.setObjectName("age")
        self.gridLayout.addWidget(self.age, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(70, 20))
        self.label_7.setMaximumSize(QtCore.QSize(70, 20))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(70, 20))
        self.label_3.setMaximumSize(QtCore.QSize(70, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(70, 20))
        self.label_9.setMaximumSize(QtCore.QSize(70, 20))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.profession = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.profession.setMinimumSize(QtCore.QSize(252, 17))
        self.profession.setMaximumSize(QtCore.QSize(252, 17))
        self.profession.setStyleSheet("background-color: transparent")
        self.profession.setFrame(False)
        self.profession.setReadOnly(True)
        self.profession.setObjectName("profession")
        self.gridLayout.addWidget(self.profession, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(70, 20))
        self.label_8.setMaximumSize(QtCore.QSize(70, 20))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.workplace = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.workplace.setMinimumSize(QtCore.QSize(252, 17))
        self.workplace.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.workplace.setStyleSheet("background-color: transparent")
        self.workplace.setFrame(False)
        self.workplace.setReadOnly(True)
        self.workplace.setObjectName("workplace")
        self.gridLayout.addWidget(self.workplace, 5, 1, 1, 1)
        self.email = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.email.setMinimumSize(QtCore.QSize(252, 17))
        self.email.setMaximumSize(QtCore.QSize(252, 17))
        self.email.setStyleSheet("background-color: transparent")
        self.email.setFrame(False)
        self.email.setReadOnly(True)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 6, 1, 1, 1)

        self.retranslateUi(showpersondata)

    def retranslateUi(self, showpersondata):
        _translate = QtCore.QCoreApplication.translate
        showpersondata.setWindowTitle(_translate("showpersondata", "个人信息"))
        self.pushButton.setText(_translate("showpersondata", "修改"))
        self.label_5.setText(_translate("showpersondata", "欢迎来到个人中心！"))
        self.location.setText(_translate("showpersondata", "无"))
        self.username.setText(_translate("showpersondata", "无"))
        self.label_4.setText(_translate("showpersondata", "<html><head/><body><p align=\"right\"><span style=\" color:#92827f;\">年龄：</span></p></body></html>"))
        self.label_2.setText(_translate("showpersondata", "<html><head/><body><p align=\"right\"><span style=\" color:#92827f;\">性别：</span></p></body></html>"))
        self.sex.setText(_translate("showpersondata", "无"))
        self.label.setText(_translate("showpersondata", "<html><head/><body><p align=\"right\"><span style=\" color:#92827f;\">姓名：</span></p></body></html>"))
        self.age.setText(_translate("showpersondata", "无"))
        self.label_7.setText(_translate("showpersondata", "<html><head/><body><p align=\"right\"><span style=\" color:#92827f;\">职业：</span></p></body></html>"))
        self.label_3.setText(_translate("showpersondata", "<html><head/><body><p align=\"right\"><span style=\" color:#92827f;\">所在地：</span></p></body></html>"))
        self.label_9.setText(_translate("showpersondata", "<html><head/><body><p align=\"right\"><span style=\" color:#92827f;\">单位：</span></p></body></html>"))
        self.profession.setText(_translate("showpersondata", "无"))
        self.label_8.setText(_translate("showpersondata", "<html><head/><body><p align=\"right\"><span style=\" color:#92827f;\">邮箱：</span></p></body></html>"))
        self.workplace.setText(_translate("showpersondata", "无"))
        self.email.setText(_translate("showpersondata", "无"))

