# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1192, 889)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setStyleSheet("#toolBar_Devices QToolButton {\n"
"width: 50px;\n"
"height: 55px;\n"
"border:solid 1px black opacity 0.4;\n"
"background-none;\n"
"}\n"
"\n"
"#toolBar_General QToolButton {\n"
"width: 36px;\n"
"height: 36px;\n"
"border:solid 1px black opacity 0.4;\n"
"background-none;\n"
"}\n"
"\n"
"")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.uiCentralWidget = QtWidgets.QWidget(MainWindow)
        self.uiCentralWidget.setObjectName("uiCentralWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.uiCentralWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_4.addLayout(self.horizontalLayout_14)
        self.iconlogo = QtWidgets.QPushButton(self.uiCentralWidget)
        self.iconlogo.setMinimumSize(QtCore.QSize(32, 32))
        self.iconlogo.setMaximumSize(QtCore.QSize(32, 32))
        self.iconlogo.setStyleSheet("")
        self.iconlogo.setText("")
        self.iconlogo.setObjectName("iconlogo")
        self.horizontalLayout_4.addWidget(self.iconlogo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.windowTitle = QtWidgets.QLabel(self.uiCentralWidget)
        self.windowTitle.setObjectName("windowTitle")
        self.horizontalLayout_4.addWidget(self.windowTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 8)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uiminimumAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiminimumAction.setMinimumSize(QtCore.QSize(32, 22))
        self.uiminimumAction.setMaximumSize(QtCore.QSize(32, 22))
        self.uiminimumAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiminimumAction.setText("")
        self.uiminimumAction.setIconSize(QtCore.QSize(32, 22))
        self.uiminimumAction.setObjectName("uiminimumAction")
        self.horizontalLayout_3.addWidget(self.uiminimumAction)
        self.uiMaximumAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiMaximumAction.setMinimumSize(QtCore.QSize(32, 22))
        self.uiMaximumAction.setMaximumSize(QtCore.QSize(32, 22))
        self.uiMaximumAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiMaximumAction.setText("")
        self.uiMaximumAction.setIconSize(QtCore.QSize(32, 22))
        self.uiMaximumAction.setObjectName("uiMaximumAction")
        self.horizontalLayout_3.addWidget(self.uiMaximumAction)
        self.uicloseAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uicloseAction.setMinimumSize(QtCore.QSize(40, 22))
        self.uicloseAction.setMaximumSize(QtCore.QSize(40, 22))
        self.uicloseAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uicloseAction.setText("")
        self.uicloseAction.setIconSize(QtCore.QSize(32, 22))
        self.uicloseAction.setObjectName("uicloseAction")
        self.horizontalLayout_3.addWidget(self.uicloseAction)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.menutab = QtWidgets.QTabWidget(self.uiCentralWidget)
        self.menutab.setMaximumSize(QtCore.QSize(16777215, 108))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.menutab.setFont(font)
        self.menutab.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color: white;\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: rgb(240,240,240);\n"
"    border-style: inset;\n"
"    }\n"
"QLabel{\n"
"    \n"
"    font: 10pt \"宋体\";\n"
"}")
        self.menutab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.menutab.setIconSize(QtCore.QSize(16, 16))
        self.menutab.setDocumentMode(False)
        self.menutab.setTabsClosable(False)
        self.menutab.setMovable(True)
        self.menutab.setTabBarAutoHide(False)
        self.menutab.setObjectName("menutab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.uiNewProjectAction = QtWidgets.QPushButton(self.tab)
        self.uiNewProjectAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiNewProjectAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiNewProjectAction.setToolTip("")
        self.uiNewProjectAction.setText("")
        self.uiNewProjectAction.setIconSize(QtCore.QSize(35, 35))
        self.uiNewProjectAction.setObjectName("uiNewProjectAction")
        self.verticalLayout_11.addWidget(self.uiNewProjectAction)
        self.NewProjectAction = QtWidgets.QLabel(self.tab)
        self.NewProjectAction.setMinimumSize(QtCore.QSize(40, 14))
        self.NewProjectAction.setMaximumSize(QtCore.QSize(40, 14))
        self.NewProjectAction.setObjectName("NewProjectAction")
        self.verticalLayout_11.addWidget(self.NewProjectAction)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.uiOpenProjectAction = QtWidgets.QPushButton(self.tab)
        self.uiOpenProjectAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiOpenProjectAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiOpenProjectAction.setToolTip("")
        self.uiOpenProjectAction.setText("")
        self.uiOpenProjectAction.setIconSize(QtCore.QSize(35, 35))
        self.uiOpenProjectAction.setObjectName("uiOpenProjectAction")
        self.verticalLayout_23.addWidget(self.uiOpenProjectAction)
        self.OpenProjectAction = QtWidgets.QLabel(self.tab)
        self.OpenProjectAction.setMinimumSize(QtCore.QSize(40, 14))
        self.OpenProjectAction.setMaximumSize(QtCore.QSize(40, 14))
        self.OpenProjectAction.setObjectName("OpenProjectAction")
        self.verticalLayout_23.addWidget(self.OpenProjectAction)
        self.horizontalLayout_5.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.uiSaveProjectAsAction = QtWidgets.QPushButton(self.tab)
        self.uiSaveProjectAsAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiSaveProjectAsAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiSaveProjectAsAction.setToolTip("")
        self.uiSaveProjectAsAction.setText("")
        self.uiSaveProjectAsAction.setIconSize(QtCore.QSize(35, 35))
        self.uiSaveProjectAsAction.setObjectName("uiSaveProjectAsAction")
        self.verticalLayout_24.addWidget(self.uiSaveProjectAsAction)
        self.SaveProjectAsAction = QtWidgets.QLabel(self.tab)
        self.SaveProjectAsAction.setMinimumSize(QtCore.QSize(40, 14))
        self.SaveProjectAsAction.setMaximumSize(QtCore.QSize(40, 14))
        self.SaveProjectAsAction.setObjectName("SaveProjectAsAction")
        self.verticalLayout_24.addWidget(self.SaveProjectAsAction)
        self.horizontalLayout_5.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_5.addLayout(self.verticalLayout_25)
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.uiImportProjectAction = QtWidgets.QPushButton(self.tab)
        self.uiImportProjectAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiImportProjectAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiImportProjectAction.setToolTip("")
        self.uiImportProjectAction.setText("")
        self.uiImportProjectAction.setIconSize(QtCore.QSize(35, 35))
        self.uiImportProjectAction.setObjectName("uiImportProjectAction")
        self.verticalLayout_26.addWidget(self.uiImportProjectAction)
        self.ImportProjectAction = QtWidgets.QLabel(self.tab)
        self.ImportProjectAction.setMinimumSize(QtCore.QSize(40, 14))
        self.ImportProjectAction.setMaximumSize(QtCore.QSize(40, 14))
        self.ImportProjectAction.setObjectName("ImportProjectAction")
        self.verticalLayout_26.addWidget(self.ImportProjectAction)
        self.horizontalLayout_5.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.uiExportProjectAction = QtWidgets.QPushButton(self.tab)
        self.uiExportProjectAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiExportProjectAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiExportProjectAction.setToolTip("")
        self.uiExportProjectAction.setText("")
        self.uiExportProjectAction.setIconSize(QtCore.QSize(35, 35))
        self.uiExportProjectAction.setObjectName("uiExportProjectAction")
        self.verticalLayout_27.addWidget(self.uiExportProjectAction)
        self.ExportProjectAction = QtWidgets.QLabel(self.tab)
        self.ExportProjectAction.setMinimumSize(QtCore.QSize(40, 14))
        self.ExportProjectAction.setMaximumSize(QtCore.QSize(40, 14))
        self.ExportProjectAction.setObjectName("ExportProjectAction")
        self.verticalLayout_27.addWidget(self.ExportProjectAction)
        self.horizontalLayout_5.addLayout(self.verticalLayout_27)
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_5.addWidget(self.line_5)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.uiQuitAction = QtWidgets.QPushButton(self.tab)
        self.uiQuitAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiQuitAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiQuitAction.setToolTip("")
        self.uiQuitAction.setText("")
        self.uiQuitAction.setIconSize(QtCore.QSize(35, 35))
        self.uiQuitAction.setObjectName("uiQuitAction")
        self.verticalLayout_28.addWidget(self.uiQuitAction)
        self.QuitAction = QtWidgets.QLabel(self.tab)
        self.QuitAction.setMinimumSize(QtCore.QSize(40, 14))
        self.QuitAction.setMaximumSize(QtCore.QSize(40, 14))
        self.QuitAction.setObjectName("QuitAction")
        self.verticalLayout_28.addWidget(self.QuitAction)
        self.horizontalLayout_5.addLayout(self.verticalLayout_28)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.menutab.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.uigeneralPreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uigeneralPreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uigeneralPreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uigeneralPreferencesAction.setToolTip("")
        self.uigeneralPreferencesAction.setText("")
        self.uigeneralPreferencesAction.setIconSize(QtCore.QSize(35, 35))
        self.uigeneralPreferencesAction.setObjectName("uigeneralPreferencesAction")
        self.verticalLayout_53.addWidget(self.uigeneralPreferencesAction)
        self.generalPreferencesAction = QtWidgets.QLabel(self.tab_3)
        self.generalPreferencesAction.setMinimumSize(QtCore.QSize(40, 14))
        self.generalPreferencesAction.setMaximumSize(QtCore.QSize(40, 14))
        self.generalPreferencesAction.setObjectName("generalPreferencesAction")
        self.verticalLayout_53.addWidget(self.generalPreferencesAction)
        self.horizontalLayout_9.addLayout(self.verticalLayout_53)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.uiserverPreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uiserverPreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiserverPreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiserverPreferencesAction.setToolTip("")
        self.uiserverPreferencesAction.setText("")
        self.uiserverPreferencesAction.setIconSize(QtCore.QSize(35, 35))
        self.uiserverPreferencesAction.setObjectName("uiserverPreferencesAction")
        self.verticalLayout_49.addWidget(self.uiserverPreferencesAction)
        self.serverPreferencesAction = QtWidgets.QLabel(self.tab_3)
        self.serverPreferencesAction.setMinimumSize(QtCore.QSize(40, 14))
        self.serverPreferencesAction.setMaximumSize(QtCore.QSize(40, 14))
        self.serverPreferencesAction.setObjectName("serverPreferencesAction")
        self.verticalLayout_49.addWidget(self.serverPreferencesAction)
        self.horizontalLayout_9.addLayout(self.verticalLayout_49)
        self.verticalLayout_54 = QtWidgets.QVBoxLayout()
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.uiwiresharkPreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uiwiresharkPreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiwiresharkPreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiwiresharkPreferencesAction.setToolTip("")
        self.uiwiresharkPreferencesAction.setText("")
        self.uiwiresharkPreferencesAction.setIconSize(QtCore.QSize(35, 35))
        self.uiwiresharkPreferencesAction.setObjectName("uiwiresharkPreferencesAction")
        self.verticalLayout_54.addWidget(self.uiwiresharkPreferencesAction)
        self.wiresharkPreferencesAction = QtWidgets.QLabel(self.tab_3)
        self.wiresharkPreferencesAction.setMinimumSize(QtCore.QSize(40, 14))
        self.wiresharkPreferencesAction.setMaximumSize(QtCore.QSize(40, 14))
        self.wiresharkPreferencesAction.setObjectName("wiresharkPreferencesAction")
        self.verticalLayout_54.addWidget(self.wiresharkPreferencesAction)
        self.horizontalLayout_9.addLayout(self.verticalLayout_54)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.uivpcsPreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uivpcsPreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uivpcsPreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uivpcsPreferencesAction.setToolTip("")
        self.uivpcsPreferencesAction.setText("")
        self.uivpcsPreferencesAction.setIconSize(QtCore.QSize(35, 35))
        self.uivpcsPreferencesAction.setObjectName("uivpcsPreferencesAction")
        self.verticalLayout_51.addWidget(self.uivpcsPreferencesAction)
        self.vpcsPreferencesAction = QtWidgets.QLabel(self.tab_3)
        self.vpcsPreferencesAction.setMinimumSize(QtCore.QSize(40, 14))
        self.vpcsPreferencesAction.setMaximumSize(QtCore.QSize(40, 14))
        self.vpcsPreferencesAction.setObjectName("vpcsPreferencesAction")
        self.verticalLayout_51.addWidget(self.vpcsPreferencesAction)
        self.horizontalLayout_9.addLayout(self.verticalLayout_51)
        self.verticalLayout_66 = QtWidgets.QVBoxLayout()
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.uidynamipsPreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uidynamipsPreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uidynamipsPreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uidynamipsPreferencesAction.setToolTip("")
        self.uidynamipsPreferencesAction.setText("")
        self.uidynamipsPreferencesAction.setIconSize(QtCore.QSize(35, 35))
        self.uidynamipsPreferencesAction.setObjectName("uidynamipsPreferencesAction")
        self.verticalLayout_66.addWidget(self.uidynamipsPreferencesAction)
        self.dynamipsPreferencesAction = QtWidgets.QLabel(self.tab_3)
        self.dynamipsPreferencesAction.setMinimumSize(QtCore.QSize(40, 14))
        self.dynamipsPreferencesAction.setMaximumSize(QtCore.QSize(40, 14))
        self.dynamipsPreferencesAction.setObjectName("dynamipsPreferencesAction")
        self.verticalLayout_66.addWidget(self.dynamipsPreferencesAction)
        self.horizontalLayout_9.addLayout(self.verticalLayout_66)
        self.verticalLayout_65 = QtWidgets.QVBoxLayout()
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.uiunixPreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uiunixPreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiunixPreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiunixPreferencesAction.setToolTip("")
        self.uiunixPreferencesAction.setText("")
        self.uiunixPreferencesAction.setIconSize(QtCore.QSize(35, 35))
        self.uiunixPreferencesAction.setObjectName("uiunixPreferencesAction")
        self.verticalLayout_65.addWidget(self.uiunixPreferencesAction)
        self.unixPreferencesAction = QtWidgets.QLabel(self.tab_3)
        self.unixPreferencesAction.setMinimumSize(QtCore.QSize(40, 14))
        self.unixPreferencesAction.setMaximumSize(QtCore.QSize(40, 14))
        self.unixPreferencesAction.setObjectName("unixPreferencesAction")
        self.verticalLayout_65.addWidget(self.unixPreferencesAction)
        self.horizontalLayout_9.addLayout(self.verticalLayout_65)
        self.verticalLayout_64 = QtWidgets.QVBoxLayout()
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.uivmwarePreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uivmwarePreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uivmwarePreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uivmwarePreferencesAction.setToolTip("")
        self.uivmwarePreferencesAction.setText("")
        self.uivmwarePreferencesAction.setIconSize(QtCore.QSize(35, 35))
        self.uivmwarePreferencesAction.setObjectName("uivmwarePreferencesAction")
        self.verticalLayout_64.addWidget(self.uivmwarePreferencesAction)
        self.vmwarePreferencesAction = QtWidgets.QLabel(self.tab_3)
        self.vmwarePreferencesAction.setMinimumSize(QtCore.QSize(40, 14))
        self.vmwarePreferencesAction.setMaximumSize(QtCore.QSize(40, 14))
        self.vmwarePreferencesAction.setObjectName("vmwarePreferencesAction")
        self.verticalLayout_64.addWidget(self.vmwarePreferencesAction)
        self.horizontalLayout_9.addLayout(self.verticalLayout_64)
        self.line_13 = QtWidgets.QFrame(self.tab_3)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_9.addWidget(self.line_13)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.uirouterPreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uirouterPreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uirouterPreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uirouterPreferencesAction.setToolTip("")
        self.uirouterPreferencesAction.setText("")
        self.uirouterPreferencesAction.setIconSize(QtCore.QSize(35, 35))
        self.uirouterPreferencesAction.setObjectName("uirouterPreferencesAction")
        self.verticalLayout_50.addWidget(self.uirouterPreferencesAction)
        self.routerPreferencesAction = QtWidgets.QLabel(self.tab_3)
        self.routerPreferencesAction.setMinimumSize(QtCore.QSize(40, 14))
        self.routerPreferencesAction.setMaximumSize(QtCore.QSize(40, 14))
        self.routerPreferencesAction.setObjectName("routerPreferencesAction")
        self.verticalLayout_50.addWidget(self.routerPreferencesAction)
        self.horizontalLayout_9.addLayout(self.verticalLayout_50)
        self.verticalLayout_67 = QtWidgets.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.uiiouPreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uiiouPreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiiouPreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiiouPreferencesAction.setToolTip("")
        self.uiiouPreferencesAction.setText("")
        self.uiiouPreferencesAction.setIconSize(QtCore.QSize(35, 35))
        self.uiiouPreferencesAction.setObjectName("uiiouPreferencesAction")
        self.verticalLayout_67.addWidget(self.uiiouPreferencesAction)
        self.iouPreferencesAction = QtWidgets.QLabel(self.tab_3)
        self.iouPreferencesAction.setMinimumSize(QtCore.QSize(40, 14))
        self.iouPreferencesAction.setMaximumSize(QtCore.QSize(40, 14))
        self.iouPreferencesAction.setObjectName("iouPreferencesAction")
        self.verticalLayout_67.addWidget(self.iouPreferencesAction)
        self.horizontalLayout_9.addLayout(self.verticalLayout_67)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.uihospitalPreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uihospitalPreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uihospitalPreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uihospitalPreferencesAction.setToolTip("")
        self.uihospitalPreferencesAction.setText("")
        self.uihospitalPreferencesAction.setIconSize(QtCore.QSize(35, 35))
        self.uihospitalPreferencesAction.setObjectName("uihospitalPreferencesAction")
        self.verticalLayout_52.addWidget(self.uihospitalPreferencesAction)
        self.hospitalPreferencesAction = QtWidgets.QLabel(self.tab_3)
        self.hospitalPreferencesAction.setMinimumSize(QtCore.QSize(40, 14))
        self.hospitalPreferencesAction.setMaximumSize(QtCore.QSize(40, 14))
        self.hospitalPreferencesAction.setObjectName("hospitalPreferencesAction")
        self.verticalLayout_52.addWidget(self.hospitalPreferencesAction)
        self.horizontalLayout_9.addLayout(self.verticalLayout_52)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.menutab.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.uiStartAllAction = QtWidgets.QPushButton(self.tab_2)
        self.uiStartAllAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiStartAllAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiStartAllAction.setToolTip("")
        self.uiStartAllAction.setText("")
        self.uiStartAllAction.setIconSize(QtCore.QSize(25, 25))
        self.uiStartAllAction.setObjectName("uiStartAllAction")
        self.verticalLayout_10.addWidget(self.uiStartAllAction)
        self.StartAllAction = QtWidgets.QLabel(self.tab_2)
        self.StartAllAction.setMinimumSize(QtCore.QSize(30, 14))
        self.StartAllAction.setMaximumSize(QtCore.QSize(30, 14))
        self.StartAllAction.setObjectName("StartAllAction")
        self.verticalLayout_10.addWidget(self.StartAllAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.uiSuspendAllAction = QtWidgets.QPushButton(self.tab_2)
        self.uiSuspendAllAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiSuspendAllAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiSuspendAllAction.setToolTip("")
        self.uiSuspendAllAction.setText("")
        self.uiSuspendAllAction.setIconSize(QtCore.QSize(25, 25))
        self.uiSuspendAllAction.setObjectName("uiSuspendAllAction")
        self.verticalLayout_33.addWidget(self.uiSuspendAllAction)
        self.SuspendAllAction = QtWidgets.QLabel(self.tab_2)
        self.SuspendAllAction.setMinimumSize(QtCore.QSize(30, 14))
        self.SuspendAllAction.setMaximumSize(QtCore.QSize(30, 14))
        self.SuspendAllAction.setObjectName("SuspendAllAction")
        self.verticalLayout_33.addWidget(self.SuspendAllAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_33)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.uiStopAllAction = QtWidgets.QPushButton(self.tab_2)
        self.uiStopAllAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiStopAllAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiStopAllAction.setToolTip("")
        self.uiStopAllAction.setText("")
        self.uiStopAllAction.setIconSize(QtCore.QSize(25, 25))
        self.uiStopAllAction.setObjectName("uiStopAllAction")
        self.verticalLayout_34.addWidget(self.uiStopAllAction)
        self.StopAllAction = QtWidgets.QLabel(self.tab_2)
        self.StopAllAction.setMinimumSize(QtCore.QSize(30, 14))
        self.StopAllAction.setMaximumSize(QtCore.QSize(30, 14))
        self.StopAllAction.setObjectName("StopAllAction")
        self.verticalLayout_34.addWidget(self.StopAllAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_34)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.uiReloadAllAction = QtWidgets.QPushButton(self.tab_2)
        self.uiReloadAllAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiReloadAllAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiReloadAllAction.setToolTip("")
        self.uiReloadAllAction.setText("")
        self.uiReloadAllAction.setIconSize(QtCore.QSize(25, 25))
        self.uiReloadAllAction.setObjectName("uiReloadAllAction")
        self.verticalLayout_32.addWidget(self.uiReloadAllAction)
        self.ReloadAllAction = QtWidgets.QLabel(self.tab_2)
        self.ReloadAllAction.setMinimumSize(QtCore.QSize(30, 14))
        self.ReloadAllAction.setMaximumSize(QtCore.QSize(30, 14))
        self.ReloadAllAction.setObjectName("ReloadAllAction")
        self.verticalLayout_32.addWidget(self.ReloadAllAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_32)
        self.verticalLayout_63 = QtWidgets.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.uiAddLinkAction = QtWidgets.QPushButton(self.tab_2)
        self.uiAddLinkAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiAddLinkAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiAddLinkAction.setToolTip("")
        self.uiAddLinkAction.setText("")
        self.uiAddLinkAction.setIconSize(QtCore.QSize(25, 25))
        self.uiAddLinkAction.setObjectName("uiAddLinkAction")
        self.verticalLayout_63.addWidget(self.uiAddLinkAction)
        self.AddLinkAction = QtWidgets.QLabel(self.tab_2)
        self.AddLinkAction.setMinimumSize(QtCore.QSize(30, 14))
        self.AddLinkAction.setMaximumSize(QtCore.QSize(30, 14))
        self.AddLinkAction.setObjectName("AddLinkAction")
        self.verticalLayout_63.addWidget(self.AddLinkAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_63)
        self.line_12 = QtWidgets.QFrame(self.tab_2)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_7.addWidget(self.line_12)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.uiShowPortNamesAction = QtWidgets.QPushButton(self.tab_2)
        self.uiShowPortNamesAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiShowPortNamesAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiShowPortNamesAction.setToolTip("")
        self.uiShowPortNamesAction.setText("")
        self.uiShowPortNamesAction.setIconSize(QtCore.QSize(25, 25))
        self.uiShowPortNamesAction.setObjectName("uiShowPortNamesAction")
        self.verticalLayout_40.addWidget(self.uiShowPortNamesAction)
        self.ShowPortNamesAction = QtWidgets.QLabel(self.tab_2)
        self.ShowPortNamesAction.setMinimumSize(QtCore.QSize(30, 14))
        self.ShowPortNamesAction.setMaximumSize(QtCore.QSize(30, 14))
        self.ShowPortNamesAction.setObjectName("ShowPortNamesAction")
        self.verticalLayout_40.addWidget(self.ShowPortNamesAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_40)
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.uiConfigAllAction = QtWidgets.QPushButton(self.tab_2)
        self.uiConfigAllAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiConfigAllAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiConfigAllAction.setToolTip("")
        self.uiConfigAllAction.setText("")
        self.uiConfigAllAction.setIconSize(QtCore.QSize(25, 25))
        self.uiConfigAllAction.setObjectName("uiConfigAllAction")
        self.verticalLayout_41.addWidget(self.uiConfigAllAction)
        self.ConfigAllAction = QtWidgets.QLabel(self.tab_2)
        self.ConfigAllAction.setMinimumSize(QtCore.QSize(30, 14))
        self.ConfigAllAction.setMaximumSize(QtCore.QSize(30, 14))
        self.ConfigAllAction.setObjectName("ConfigAllAction")
        self.verticalLayout_41.addWidget(self.ConfigAllAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_41)
        self.line_7 = QtWidgets.QFrame(self.tab_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_7.addWidget(self.line_7)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.uiZoomInAction = QtWidgets.QPushButton(self.tab_2)
        self.uiZoomInAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiZoomInAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiZoomInAction.setToolTip("")
        self.uiZoomInAction.setText("")
        self.uiZoomInAction.setIconSize(QtCore.QSize(25, 25))
        self.uiZoomInAction.setObjectName("uiZoomInAction")
        self.verticalLayout_30.addWidget(self.uiZoomInAction)
        self.ZoomInAction = QtWidgets.QLabel(self.tab_2)
        self.ZoomInAction.setMinimumSize(QtCore.QSize(30, 14))
        self.ZoomInAction.setMaximumSize(QtCore.QSize(30, 14))
        self.ZoomInAction.setObjectName("ZoomInAction")
        self.verticalLayout_30.addWidget(self.ZoomInAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_30)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.uiZoomOutAction = QtWidgets.QPushButton(self.tab_2)
        self.uiZoomOutAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiZoomOutAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiZoomOutAction.setToolTip("")
        self.uiZoomOutAction.setText("")
        self.uiZoomOutAction.setIconSize(QtCore.QSize(25, 25))
        self.uiZoomOutAction.setObjectName("uiZoomOutAction")
        self.verticalLayout_35.addWidget(self.uiZoomOutAction)
        self.ZoomOutAction = QtWidgets.QLabel(self.tab_2)
        self.ZoomOutAction.setMinimumSize(QtCore.QSize(30, 14))
        self.ZoomOutAction.setMaximumSize(QtCore.QSize(30, 14))
        self.ZoomOutAction.setObjectName("ZoomOutAction")
        self.verticalLayout_35.addWidget(self.ZoomOutAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_35)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.uiScreenshotAction = QtWidgets.QPushButton(self.tab_2)
        self.uiScreenshotAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiScreenshotAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiScreenshotAction.setToolTip("")
        self.uiScreenshotAction.setText("")
        self.uiScreenshotAction.setIconSize(QtCore.QSize(25, 25))
        self.uiScreenshotAction.setObjectName("uiScreenshotAction")
        self.verticalLayout_42.addWidget(self.uiScreenshotAction)
        self.ScreenshotAction = QtWidgets.QLabel(self.tab_2)
        self.ScreenshotAction.setMinimumSize(QtCore.QSize(30, 14))
        self.ScreenshotAction.setMaximumSize(QtCore.QSize(30, 14))
        self.ScreenshotAction.setObjectName("ScreenshotAction")
        self.verticalLayout_42.addWidget(self.ScreenshotAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_42)
        self.line_8 = QtWidgets.QFrame(self.tab_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_7.addWidget(self.line_8)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.uiShowLayersAction = QtWidgets.QCheckBox(self.tab_2)
        self.uiShowLayersAction.setMinimumSize(QtCore.QSize(71, 16))
        self.uiShowLayersAction.setMaximumSize(QtCore.QSize(71, 16))
        self.uiShowLayersAction.setToolTip("")
        self.uiShowLayersAction.setObjectName("uiShowLayersAction")
        self.verticalLayout_8.addWidget(self.uiShowLayersAction)
        self.uiShowGridAction = QtWidgets.QCheckBox(self.tab_2)
        self.uiShowGridAction.setMinimumSize(QtCore.QSize(71, 16))
        self.uiShowGridAction.setMaximumSize(QtCore.QSize(71, 16))
        self.uiShowGridAction.setToolTip("")
        self.uiShowGridAction.setObjectName("uiShowGridAction")
        self.verticalLayout_8.addWidget(self.uiShowGridAction)
        self.uiSnapToGridAction = QtWidgets.QCheckBox(self.tab_2)
        self.uiSnapToGridAction.setMinimumSize(QtCore.QSize(85, 16))
        self.uiSnapToGridAction.setMaximumSize(QtCore.QSize(71, 16))
        self.uiSnapToGridAction.setToolTip("")
        self.uiSnapToGridAction.setObjectName("uiSnapToGridAction")
        self.verticalLayout_8.addWidget(self.uiSnapToGridAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.line_9 = QtWidgets.QFrame(self.tab_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_7.addWidget(self.line_9)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.uiInsertImageAction = QtWidgets.QPushButton(self.tab_2)
        self.uiInsertImageAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiInsertImageAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiInsertImageAction.setToolTip("")
        self.uiInsertImageAction.setText("")
        self.uiInsertImageAction.setIconSize(QtCore.QSize(25, 25))
        self.uiInsertImageAction.setObjectName("uiInsertImageAction")
        self.verticalLayout_37.addWidget(self.uiInsertImageAction)
        self.InsertImageAction = QtWidgets.QLabel(self.tab_2)
        self.InsertImageAction.setMinimumSize(QtCore.QSize(30, 14))
        self.InsertImageAction.setMaximumSize(QtCore.QSize(30, 14))
        self.InsertImageAction.setObjectName("InsertImageAction")
        self.verticalLayout_37.addWidget(self.InsertImageAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_37)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.uiAddNoteAction = QtWidgets.QPushButton(self.tab_2)
        self.uiAddNoteAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiAddNoteAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiAddNoteAction.setToolTip("")
        self.uiAddNoteAction.setText("")
        self.uiAddNoteAction.setIconSize(QtCore.QSize(25, 25))
        self.uiAddNoteAction.setObjectName("uiAddNoteAction")
        self.verticalLayout_36.addWidget(self.uiAddNoteAction)
        self.AddNoteAction = QtWidgets.QLabel(self.tab_2)
        self.AddNoteAction.setMinimumSize(QtCore.QSize(30, 14))
        self.AddNoteAction.setMaximumSize(QtCore.QSize(30, 14))
        self.AddNoteAction.setObjectName("AddNoteAction")
        self.verticalLayout_36.addWidget(self.AddNoteAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_36)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.uiDrawEllipseAction = QtWidgets.QPushButton(self.tab_2)
        self.uiDrawEllipseAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiDrawEllipseAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiDrawEllipseAction.setToolTip("")
        self.uiDrawEllipseAction.setText("")
        self.uiDrawEllipseAction.setIconSize(QtCore.QSize(25, 25))
        self.uiDrawEllipseAction.setObjectName("uiDrawEllipseAction")
        self.verticalLayout_38.addWidget(self.uiDrawEllipseAction)
        self.DrawEllipseAction = QtWidgets.QLabel(self.tab_2)
        self.DrawEllipseAction.setMinimumSize(QtCore.QSize(30, 14))
        self.DrawEllipseAction.setMaximumSize(QtCore.QSize(30, 14))
        self.DrawEllipseAction.setObjectName("DrawEllipseAction")
        self.verticalLayout_38.addWidget(self.DrawEllipseAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_38)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.uiDrawRectangleAction = QtWidgets.QPushButton(self.tab_2)
        self.uiDrawRectangleAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiDrawRectangleAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiDrawRectangleAction.setToolTip("")
        self.uiDrawRectangleAction.setText("")
        self.uiDrawRectangleAction.setIconSize(QtCore.QSize(25, 25))
        self.uiDrawRectangleAction.setObjectName("uiDrawRectangleAction")
        self.verticalLayout_39.addWidget(self.uiDrawRectangleAction)
        self.DrawRectangleAction = QtWidgets.QLabel(self.tab_2)
        self.DrawRectangleAction.setMinimumSize(QtCore.QSize(30, 14))
        self.DrawRectangleAction.setMaximumSize(QtCore.QSize(30, 14))
        self.DrawRectangleAction.setObjectName("DrawRectangleAction")
        self.verticalLayout_39.addWidget(self.DrawRectangleAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_39)
        self.line_10 = QtWidgets.QFrame(self.tab_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_7.addWidget(self.line_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.uiShowTopology = QtWidgets.QCheckBox(self.tab_2)
        self.uiShowTopology.setMinimumSize(QtCore.QSize(100, 16))
        self.uiShowTopology.setMaximumSize(QtCore.QSize(100, 16))
        self.uiShowTopology.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.uiShowTopology.setObjectName("uiShowTopology")
        self.verticalLayout_9.addWidget(self.uiShowTopology)
        self.uiShowServer = QtWidgets.QCheckBox(self.tab_2)
        self.uiShowServer.setMinimumSize(QtCore.QSize(100, 16))
        self.uiShowServer.setMaximumSize(QtCore.QSize(100, 16))
        self.uiShowServer.setObjectName("uiShowServer")
        self.verticalLayout_9.addWidget(self.uiShowServer)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.horizontalLayout_7.addLayout(self.verticalLayout_44)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.horizontalLayout_7.addLayout(self.verticalLayout_43)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.menutab.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.uiWareAction = QtWidgets.QPushButton(self.tab_4)
        self.uiWareAction.setMinimumSize(QtCore.QSize(50, 50))
        self.uiWareAction.setMaximumSize(QtCore.QSize(50, 50))
        self.uiWareAction.setToolTip("")
        self.uiWareAction.setText("")
        self.uiWareAction.setIconSize(QtCore.QSize(45, 45))
        self.uiWareAction.setObjectName("uiWareAction")
        self.verticalLayout_57.addWidget(self.uiWareAction)
        self.WareAction = QtWidgets.QLabel(self.tab_4)
        self.WareAction.setMinimumSize(QtCore.QSize(50, 14))
        self.WareAction.setMaximumSize(QtCore.QSize(50, 14))
        self.WareAction.setObjectName("WareAction")
        self.verticalLayout_57.addWidget(self.WareAction)
        self.horizontalLayout_11.addLayout(self.verticalLayout_57)
        self.verticalLayout_68 = QtWidgets.QVBoxLayout()
        self.verticalLayout_68.setObjectName("verticalLayout_68")
        self.uiExamAction = QtWidgets.QPushButton(self.tab_4)
        self.uiExamAction.setMinimumSize(QtCore.QSize(50, 50))
        self.uiExamAction.setMaximumSize(QtCore.QSize(50, 50))
        self.uiExamAction.setToolTip("")
        self.uiExamAction.setText("")
        self.uiExamAction.setIconSize(QtCore.QSize(45, 45))
        self.uiExamAction.setObjectName("uiExamAction")
        self.verticalLayout_68.addWidget(self.uiExamAction)
        self.ExamAction = QtWidgets.QLabel(self.tab_4)
        self.ExamAction.setMinimumSize(QtCore.QSize(50, 14))
        self.ExamAction.setMaximumSize(QtCore.QSize(50, 14))
        self.ExamAction.setObjectName("ExamAction")
        self.verticalLayout_68.addWidget(self.ExamAction)
        self.horizontalLayout_11.addLayout(self.verticalLayout_68)
        self.verticalLayout_70 = QtWidgets.QVBoxLayout()
        self.verticalLayout_70.setObjectName("verticalLayout_70")
        self.uiStorageAction = QtWidgets.QPushButton(self.tab_4)
        self.uiStorageAction.setMinimumSize(QtCore.QSize(50, 50))
        self.uiStorageAction.setMaximumSize(QtCore.QSize(50, 50))
        self.uiStorageAction.setToolTip("")
        self.uiStorageAction.setText("")
        self.uiStorageAction.setIconSize(QtCore.QSize(45, 45))
        self.uiStorageAction.setObjectName("uiStorageAction")
        self.verticalLayout_70.addWidget(self.uiStorageAction)
        self.StorageAction = QtWidgets.QLabel(self.tab_4)
        self.StorageAction.setMinimumSize(QtCore.QSize(50, 14))
        self.StorageAction.setMaximumSize(QtCore.QSize(50, 14))
        self.StorageAction.setObjectName("StorageAction")
        self.verticalLayout_70.addWidget(self.StorageAction)
        self.horizontalLayout_11.addLayout(self.verticalLayout_70)
        self.verticalLayout_75 = QtWidgets.QVBoxLayout()
        self.verticalLayout_75.setObjectName("verticalLayout_75")
        self.uiPaperAction = QtWidgets.QPushButton(self.tab_4)
        self.uiPaperAction.setMinimumSize(QtCore.QSize(50, 50))
        self.uiPaperAction.setMaximumSize(QtCore.QSize(50, 50))
        self.uiPaperAction.setToolTip("")
        self.uiPaperAction.setText("")
        self.uiPaperAction.setIconSize(QtCore.QSize(45, 45))
        self.uiPaperAction.setObjectName("uiPaperAction")
        self.verticalLayout_75.addWidget(self.uiPaperAction)
        self.PaperAction = QtWidgets.QLabel(self.tab_4)
        self.PaperAction.setMinimumSize(QtCore.QSize(50, 14))
        self.PaperAction.setMaximumSize(QtCore.QSize(50, 14))
        self.PaperAction.setObjectName("PaperAction")
        self.verticalLayout_75.addWidget(self.PaperAction)
        self.horizontalLayout_11.addLayout(self.verticalLayout_75)
        self.verticalLayout_73 = QtWidgets.QVBoxLayout()
        self.verticalLayout_73.setObjectName("verticalLayout_73")
        self.uiToolsAction = QtWidgets.QPushButton(self.tab_4)
        self.uiToolsAction.setMinimumSize(QtCore.QSize(50, 50))
        self.uiToolsAction.setMaximumSize(QtCore.QSize(50, 50))
        self.uiToolsAction.setToolTip("")
        self.uiToolsAction.setText("")
        self.uiToolsAction.setIconSize(QtCore.QSize(45, 45))
        self.uiToolsAction.setObjectName("uiToolsAction")
        self.verticalLayout_73.addWidget(self.uiToolsAction)
        self.ToolsAction = QtWidgets.QLabel(self.tab_4)
        self.ToolsAction.setMinimumSize(QtCore.QSize(50, 14))
        self.ToolsAction.setMaximumSize(QtCore.QSize(50, 14))
        self.ToolsAction.setObjectName("ToolsAction")
        self.verticalLayout_73.addWidget(self.ToolsAction)
        self.horizontalLayout_11.addLayout(self.verticalLayout_73)
        self.line_14 = QtWidgets.QFrame(self.tab_4)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayout_11.addWidget(self.line_14)
        self.verticalLayout_77 = QtWidgets.QVBoxLayout()
        self.verticalLayout_77.setObjectName("verticalLayout_77")
        self.uiiMNSSAction = QtWidgets.QPushButton(self.tab_4)
        self.uiiMNSSAction.setMinimumSize(QtCore.QSize(50, 50))
        self.uiiMNSSAction.setMaximumSize(QtCore.QSize(50, 50))
        self.uiiMNSSAction.setToolTip("")
        self.uiiMNSSAction.setText("")
        self.uiiMNSSAction.setIconSize(QtCore.QSize(45, 45))
        self.uiiMNSSAction.setObjectName("uiiMNSSAction")
        self.verticalLayout_77.addWidget(self.uiiMNSSAction)
        self.iMNSSAction = QtWidgets.QLabel(self.tab_4)
        self.iMNSSAction.setMinimumSize(QtCore.QSize(50, 14))
        self.iMNSSAction.setMaximumSize(QtCore.QSize(50, 14))
        self.iMNSSAction.setObjectName("iMNSSAction")
        self.verticalLayout_77.addWidget(self.iMNSSAction)
        self.horizontalLayout_11.addLayout(self.verticalLayout_77)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.menutab.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout()
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.uiCheckForUpdateAction = QtWidgets.QPushButton(self.tab_5)
        self.uiCheckForUpdateAction.setMinimumSize(QtCore.QSize(45, 45))
        self.uiCheckForUpdateAction.setMaximumSize(QtCore.QSize(45, 45))
        self.uiCheckForUpdateAction.setToolTip("")
        self.uiCheckForUpdateAction.setText("")
        self.uiCheckForUpdateAction.setIconSize(QtCore.QSize(40, 40))
        self.uiCheckForUpdateAction.setObjectName("uiCheckForUpdateAction")
        self.verticalLayout_61.addWidget(self.uiCheckForUpdateAction)
        self.CheckForUpdateAction = QtWidgets.QLabel(self.tab_5)
        self.CheckForUpdateAction.setMinimumSize(QtCore.QSize(45, 14))
        self.CheckForUpdateAction.setMaximumSize(QtCore.QSize(45, 14))
        self.CheckForUpdateAction.setObjectName("CheckForUpdateAction")
        self.verticalLayout_61.addWidget(self.CheckForUpdateAction)
        self.horizontalLayout_15.addLayout(self.verticalLayout_61)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.uiOnlineHelpAction = QtWidgets.QPushButton(self.tab_5)
        self.uiOnlineHelpAction.setMinimumSize(QtCore.QSize(45, 45))
        self.uiOnlineHelpAction.setMaximumSize(QtCore.QSize(45, 45))
        self.uiOnlineHelpAction.setToolTip("")
        self.uiOnlineHelpAction.setText("")
        self.uiOnlineHelpAction.setIconSize(QtCore.QSize(40, 40))
        self.uiOnlineHelpAction.setObjectName("uiOnlineHelpAction")
        self.verticalLayout_45.addWidget(self.uiOnlineHelpAction)
        self.OnlineHelpAction = QtWidgets.QLabel(self.tab_5)
        self.OnlineHelpAction.setMinimumSize(QtCore.QSize(45, 14))
        self.OnlineHelpAction.setMaximumSize(QtCore.QSize(45, 14))
        self.OnlineHelpAction.setObjectName("OnlineHelpAction")
        self.verticalLayout_45.addWidget(self.OnlineHelpAction)
        self.horizontalLayout_15.addLayout(self.verticalLayout_45)
        self.verticalLayout_60 = QtWidgets.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.uiExportDebugInformationAction = QtWidgets.QPushButton(self.tab_5)
        self.uiExportDebugInformationAction.setMinimumSize(QtCore.QSize(45, 45))
        self.uiExportDebugInformationAction.setMaximumSize(QtCore.QSize(45, 45))
        self.uiExportDebugInformationAction.setText("")
        self.uiExportDebugInformationAction.setIconSize(QtCore.QSize(40, 40))
        self.uiExportDebugInformationAction.setObjectName("uiExportDebugInformationAction")
        self.verticalLayout_60.addWidget(self.uiExportDebugInformationAction)
        self.ExportDebugInformationAction = QtWidgets.QLabel(self.tab_5)
        self.ExportDebugInformationAction.setMinimumSize(QtCore.QSize(45, 14))
        self.ExportDebugInformationAction.setMaximumSize(QtCore.QSize(45, 14))
        self.ExportDebugInformationAction.setToolTip("")
        self.ExportDebugInformationAction.setObjectName("ExportDebugInformationAction")
        self.verticalLayout_60.addWidget(self.ExportDebugInformationAction)
        self.horizontalLayout_15.addLayout(self.verticalLayout_60)
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.uiDoctorAction = QtWidgets.QPushButton(self.tab_5)
        self.uiDoctorAction.setMinimumSize(QtCore.QSize(45, 45))
        self.uiDoctorAction.setMaximumSize(QtCore.QSize(45, 45))
        self.uiDoctorAction.setToolTip("")
        self.uiDoctorAction.setText("")
        self.uiDoctorAction.setIconSize(QtCore.QSize(40, 40))
        self.uiDoctorAction.setObjectName("uiDoctorAction")
        self.verticalLayout_59.addWidget(self.uiDoctorAction)
        self.DoctorAction = QtWidgets.QLabel(self.tab_5)
        self.DoctorAction.setMinimumSize(QtCore.QSize(45, 14))
        self.DoctorAction.setMaximumSize(QtCore.QSize(45, 14))
        self.DoctorAction.setObjectName("DoctorAction")
        self.verticalLayout_59.addWidget(self.DoctorAction)
        self.horizontalLayout_15.addLayout(self.verticalLayout_59)
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.uiAboutAction = QtWidgets.QPushButton(self.tab_5)
        self.uiAboutAction.setMinimumSize(QtCore.QSize(45, 45))
        self.uiAboutAction.setMaximumSize(QtCore.QSize(45, 45))
        self.uiAboutAction.setToolTip("")
        self.uiAboutAction.setText("")
        self.uiAboutAction.setIconSize(QtCore.QSize(40, 40))
        self.uiAboutAction.setObjectName("uiAboutAction")
        self.verticalLayout_46.addWidget(self.uiAboutAction)
        self.AboutAction = QtWidgets.QLabel(self.tab_5)
        self.AboutAction.setMinimumSize(QtCore.QSize(45, 14))
        self.AboutAction.setMaximumSize(QtCore.QSize(45, 14))
        self.AboutAction.setObjectName("AboutAction")
        self.verticalLayout_46.addWidget(self.AboutAction)
        self.horizontalLayout_15.addLayout(self.verticalLayout_46)
        self.line_11 = QtWidgets.QFrame(self.tab_5)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_15.addWidget(self.line_11)
        self.verticalLayout_71 = QtWidgets.QVBoxLayout()
        self.verticalLayout_71.setObjectName("verticalLayout_71")
        self.uiGuideAction = QtWidgets.QPushButton(self.tab_5)
        self.uiGuideAction.setMinimumSize(QtCore.QSize(45, 45))
        self.uiGuideAction.setMaximumSize(QtCore.QSize(45, 45))
        self.uiGuideAction.setToolTip("")
        self.uiGuideAction.setText("")
        self.uiGuideAction.setIconSize(QtCore.QSize(40, 40))
        self.uiGuideAction.setObjectName("uiGuideAction")
        self.verticalLayout_71.addWidget(self.uiGuideAction)
        self.GuideAction = QtWidgets.QLabel(self.tab_5)
        self.GuideAction.setMinimumSize(QtCore.QSize(45, 14))
        self.GuideAction.setMaximumSize(QtCore.QSize(45, 14))
        self.GuideAction.setObjectName("GuideAction")
        self.verticalLayout_71.addWidget(self.GuideAction)
        self.horizontalLayout_15.addLayout(self.verticalLayout_71)
        self.verticalLayout_62 = QtWidgets.QVBoxLayout()
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.uiFeedbackAction = QtWidgets.QPushButton(self.tab_5)
        self.uiFeedbackAction.setMinimumSize(QtCore.QSize(45, 45))
        self.uiFeedbackAction.setMaximumSize(QtCore.QSize(45, 45))
        self.uiFeedbackAction.setToolTip("")
        self.uiFeedbackAction.setText("")
        self.uiFeedbackAction.setIconSize(QtCore.QSize(40, 40))
        self.uiFeedbackAction.setObjectName("uiFeedbackAction")
        self.verticalLayout_62.addWidget(self.uiFeedbackAction)
        self.FeedbackAction = QtWidgets.QLabel(self.tab_5)
        self.FeedbackAction.setMinimumSize(QtCore.QSize(45, 14))
        self.FeedbackAction.setMaximumSize(QtCore.QSize(45, 14))
        self.FeedbackAction.setObjectName("FeedbackAction")
        self.verticalLayout_62.addWidget(self.FeedbackAction)
        self.horizontalLayout_15.addLayout(self.verticalLayout_62)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.menutab.addTab(self.tab_5, "")
        self.horizontalLayout_13.addWidget(self.menutab)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.internetlable = QtWidgets.QLabel(self.uiCentralWidget)
        self.internetlable.setMinimumSize(QtCore.QSize(48, 20))
        self.internetlable.setMaximumSize(QtCore.QSize(48, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.internetlable.setFont(font)
        self.internetlable.setObjectName("internetlable")
        self.verticalLayout_6.addWidget(self.internetlable)
        self.uiBrowseRoutersAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseRoutersAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseRoutersAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseRoutersAction.setToolTip("")
        self.uiBrowseRoutersAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseRoutersAction.setText("")
        self.uiBrowseRoutersAction.setIconSize(QtCore.QSize(48, 48))
        self.uiBrowseRoutersAction.setObjectName("uiBrowseRoutersAction")
        self.verticalLayout_6.addWidget(self.uiBrowseRoutersAction)
        self.uiBrowseSwitchesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseSwitchesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseSwitchesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseSwitchesAction.setToolTip("")
        self.uiBrowseSwitchesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseSwitchesAction.setText("")
        self.uiBrowseSwitchesAction.setIconSize(QtCore.QSize(48, 48))
        self.uiBrowseSwitchesAction.setObjectName("uiBrowseSwitchesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseSwitchesAction)
        self.uiBrowseSecurityDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseSecurityDevicesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseSecurityDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseSecurityDevicesAction.setToolTip("")
        self.uiBrowseSecurityDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseSecurityDevicesAction.setText("")
        self.uiBrowseSecurityDevicesAction.setIconSize(QtCore.QSize(48, 48))
        self.uiBrowseSecurityDevicesAction.setObjectName("uiBrowseSecurityDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseSecurityDevicesAction)
        self.line = QtWidgets.QFrame(self.uiCentralWidget)
        self.line.setMinimumSize(QtCore.QSize(48, 0))
        self.line.setMaximumSize(QtCore.QSize(48, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.teiminallable = QtWidgets.QLabel(self.uiCentralWidget)
        self.teiminallable.setMinimumSize(QtCore.QSize(48, 20))
        self.teiminallable.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.teiminallable.setFont(font)
        self.teiminallable.setObjectName("teiminallable")
        self.verticalLayout_6.addWidget(self.teiminallable)
        self.uiBrowseClientDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseClientDevicesAction.setMinimumSize(QtCore.QSize(48, 42))
        self.uiBrowseClientDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseClientDevicesAction.setToolTip("")
        self.uiBrowseClientDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseClientDevicesAction.setText("")
        self.uiBrowseClientDevicesAction.setIconSize(QtCore.QSize(60, 60))
        self.uiBrowseClientDevicesAction.setObjectName("uiBrowseClientDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseClientDevicesAction)
        self.uiBrowseServerDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseServerDevicesAction.setMinimumSize(QtCore.QSize(48, 42))
        self.uiBrowseServerDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseServerDevicesAction.setToolTip("")
        self.uiBrowseServerDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseServerDevicesAction.setText("")
        self.uiBrowseServerDevicesAction.setIconSize(QtCore.QSize(60, 60))
        self.uiBrowseServerDevicesAction.setObjectName("uiBrowseServerDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseServerDevicesAction)
        self.line_2 = QtWidgets.QFrame(self.uiCentralWidget)
        self.line_2.setMinimumSize(QtCore.QSize(48, 0))
        self.line_2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.uiBrowseHISDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseHISDevicesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseHISDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseHISDevicesAction.setToolTip("")
        self.uiBrowseHISDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseHISDevicesAction.setText("")
        self.uiBrowseHISDevicesAction.setIconSize(QtCore.QSize(60, 60))
        self.uiBrowseHISDevicesAction.setObjectName("uiBrowseHISDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseHISDevicesAction)
        self.uiBrowseLISDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseLISDevicesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseLISDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseLISDevicesAction.setToolTip("")
        self.uiBrowseLISDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseLISDevicesAction.setText("")
        self.uiBrowseLISDevicesAction.setIconSize(QtCore.QSize(60, 60))
        self.uiBrowseLISDevicesAction.setObjectName("uiBrowseLISDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseLISDevicesAction)
        self.uiBrowsePACSDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowsePACSDevicesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowsePACSDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowsePACSDevicesAction.setToolTip("")
        self.uiBrowsePACSDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowsePACSDevicesAction.setText("")
        self.uiBrowsePACSDevicesAction.setIconSize(QtCore.QSize(60, 60))
        self.uiBrowsePACSDevicesAction.setObjectName("uiBrowsePACSDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowsePACSDevicesAction)
        self.line_3 = QtWidgets.QFrame(self.uiCentralWidget)
        self.line_3.setMaximumSize(QtCore.QSize(48, 16777215))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.connection = QtWidgets.QLabel(self.uiCentralWidget)
        self.connection.setMinimumSize(QtCore.QSize(48, 20))
        self.connection.setMaximumSize(QtCore.QSize(48, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.connection.setFont(font)
        self.connection.setObjectName("connection")
        self.verticalLayout_6.addWidget(self.connection)
        self.uiBrowseConnectDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseConnectDevicesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseConnectDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseConnectDevicesAction.setToolTip("")
        self.uiBrowseConnectDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseConnectDevicesAction.setText("")
        self.uiBrowseConnectDevicesAction.setIconSize(QtCore.QSize(60, 60))
        self.uiBrowseConnectDevicesAction.setObjectName("uiBrowseConnectDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseConnectDevicesAction)
        self.line_15 = QtWidgets.QFrame(self.uiCentralWidget)
        self.line_15.setMinimumSize(QtCore.QSize(48, 0))
        self.line_15.setMaximumSize(QtCore.QSize(48, 0))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_6.addWidget(self.line_15)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiNodesDockWidget = QtWidgets.QDockWidget(self.uiCentralWidget)
        self.uiNodesDockWidget.setEnabled(True)
        self.uiNodesDockWidget.setMinimumSize(QtCore.QSize(220, 480))
        self.uiNodesDockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.uiNodesDockWidget.setFont(font)
        self.uiNodesDockWidget.setVisible(True)
        self.uiNodesDockWidget.setFloating(False)
        self.uiNodesDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable)
        self.uiNodesDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.uiNodesDockWidget.setObjectName("uiNodesDockWidget")
        self.uiNodesDockWidgetContents = QtWidgets.QWidget()
        self.uiNodesDockWidgetContents.setObjectName("uiNodesDockWidgetContents")
        self._2 = QtWidgets.QVBoxLayout(self.uiNodesDockWidgetContents)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setSpacing(0)
        self._2.setObjectName("_2")
        self.uiNodesView = NodesView(self.uiNodesDockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiNodesView.sizePolicy().hasHeightForWidth())
        self.uiNodesView.setSizePolicy(sizePolicy)
        self.uiNodesView.setDragEnabled(False)
        self.uiNodesView.setIconSize(QtCore.QSize(32, 32))
        self.uiNodesView.setRootIsDecorated(False)
        self.uiNodesView.setObjectName("uiNodesView")
        self.uiNodesView.header().setVisible(False)
        self._2.addWidget(self.uiNodesView)
        self.uiNodesDockWidget.setWidget(self.uiNodesDockWidgetContents)
        self.horizontalLayout.addWidget(self.uiNodesDockWidget)
        self.uiGraphicsView = GraphicsView(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiGraphicsView.sizePolicy().hasHeightForWidth())
        self.uiGraphicsView.setSizePolicy(sizePolicy)
        self.uiGraphicsView.setMinimumSize(QtCore.QSize(620, 480))
        self.uiGraphicsView.setObjectName("uiGraphicsView")
        self.horizontalLayout.addWidget(self.uiGraphicsView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.uiTopologySummaryDockWidget = QtWidgets.QDockWidget(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTopologySummaryDockWidget.sizePolicy().hasHeightForWidth())
        self.uiTopologySummaryDockWidget.setSizePolicy(sizePolicy)
        self.uiTopologySummaryDockWidget.setMinimumSize(QtCore.QSize(256, 224))
        self.uiTopologySummaryDockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.uiTopologySummaryDockWidget.setFont(font)
        self.uiTopologySummaryDockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.uiTopologySummaryDockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.uiTopologySummaryDockWidget.setObjectName("uiTopologySummaryDockWidget")
        self.uiTopologySummaryDockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTopologySummaryDockWidgetContents.sizePolicy().hasHeightForWidth())
        self.uiTopologySummaryDockWidgetContents.setSizePolicy(sizePolicy)
        self.uiTopologySummaryDockWidgetContents.setObjectName("uiTopologySummaryDockWidgetContents")
        self._3 = QtWidgets.QGridLayout(self.uiTopologySummaryDockWidgetContents)
        self._3.setContentsMargins(0, 0, 0, 0)
        self._3.setSpacing(0)
        self._3.setObjectName("_3")
        self.uiTopologySummaryTreeWidget = TopologySummaryView(self.uiTopologySummaryDockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTopologySummaryTreeWidget.sizePolicy().hasHeightForWidth())
        self.uiTopologySummaryTreeWidget.setSizePolicy(sizePolicy)
        self.uiTopologySummaryTreeWidget.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.uiTopologySummaryTreeWidget.setObjectName("uiTopologySummaryTreeWidget")
        self.uiTopologySummaryTreeWidget.header().setVisible(False)
        self._3.addWidget(self.uiTopologySummaryTreeWidget, 0, 0, 1, 1)
        self.uiTopologySummaryDockWidget.setWidget(self.uiTopologySummaryDockWidgetContents)
        self.verticalLayout.addWidget(self.uiTopologySummaryDockWidget)
        self.uiServerSummaryDockWidget = QtWidgets.QDockWidget(self.uiCentralWidget)
        self.uiServerSummaryDockWidget.setMinimumSize(QtCore.QSize(256, 224))
        self.uiServerSummaryDockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.uiServerSummaryDockWidget.setFont(font)
        self.uiServerSummaryDockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.uiServerSummaryDockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.uiServerSummaryDockWidget.setObjectName("uiServerSummaryDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.uiServerSummaryTreeWidget = ServerSummaryView(self.dockWidgetContents)
        self.uiServerSummaryTreeWidget.setObjectName("uiServerSummaryTreeWidget")
        self.uiServerSummaryTreeWidget.headerItem().setText(0, "1")
        self.uiServerSummaryTreeWidget.header().setVisible(False)
        self.gridLayout.addWidget(self.uiServerSummaryTreeWidget, 0, 0, 1, 1)
        self.uiServerSummaryDockWidget.setWidget(self.dockWidgetContents)
        self.verticalLayout.addWidget(self.uiServerSummaryDockWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.showtab = QtWidgets.QTabWidget(self.uiCentralWidget)
        self.showtab.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.showtab.setFont(font)
        self.showtab.setObjectName("showtab")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.uiConsoleTextEdit = ConsoleView(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiConsoleTextEdit.sizePolicy().hasHeightForWidth())
        self.uiConsoleTextEdit.setSizePolicy(sizePolicy)
        self.uiConsoleTextEdit.setObjectName("uiConsoleTextEdit")
        self.horizontalLayout_17.addWidget(self.uiConsoleTextEdit)
        self.showtab.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_7)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.downloadarea = QtWidgets.QVBoxLayout()
        self.downloadarea.setObjectName("downloadarea")
        self.verticalLayout_13.addLayout(self.downloadarea)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.showtab.addTab(self.tab_7, "")
        self.verticalLayout_2.addWidget(self.showtab)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.uiCentralWidget)
        self.uiStatusBar = QtWidgets.QStatusBar(MainWindow)
        self.uiStatusBar.setObjectName("uiStatusBar")
        self.uilogin = QtWidgets.QPushButton()
        self.uilogin.setText("昵称")
        self.uilogin.setIconSize(QtCore.QSize(26, 26))
        self.uilogin.setStyleSheet("font: 75 14pt \"宋体\";")
        self.uilogin.setObjectName("uilogin")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Headportrait.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uilogin.setIcon(icon)
        self.uilogin.setEnabled(False)
        self.menutab.setCornerWidget(self.uilogin)
        self.showtab.setStyleSheet("font: 12pt \"宋体\";")
        MainWindow.setStatusBar(self.uiStatusBar)

        self.retranslateUi(MainWindow)
        self.menutab.setCurrentIndex(2)
        self.showtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.windowTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">MNSS(</span><span style=\" font-family:\'Calibri,sans-serif\'; font-size:16pt; font-weight:600;\">Medical Network System Simulator</span><span style=\" font-size:16pt; font-weight:600;\">)</span></p></body></html>"))
        self.uiNewProjectAction.setStatusTip(_translate("MainWindow", "新建工程"))
        self.NewProjectAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">新建</p></body></html>"))
        self.uiOpenProjectAction.setStatusTip(_translate("MainWindow", "打开工程"))
        self.OpenProjectAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">打开</p></body></html>"))
        self.uiSaveProjectAsAction.setStatusTip(_translate("MainWindow", "保存工程"))
        self.SaveProjectAsAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">保存</p></body></html>"))
        self.uiImportProjectAction.setStatusTip(_translate("MainWindow", "导入设备"))
        self.ImportProjectAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">导入</p></body></html>"))
        self.uiExportProjectAction.setStatusTip(_translate("MainWindow", "导出设备"))
        self.ExportProjectAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">导出</p></body></html>"))
        self.uiQuitAction.setStatusTip(_translate("MainWindow", "退出程序"))
        self.QuitAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">退出</p></body></html>"))
        self.menutab.setTabText(self.menutab.indexOf(self.tab), _translate("MainWindow", "文件"))
        self.uigeneralPreferencesAction.setStatusTip(_translate("MainWindow", "总设置"))
        self.generalPreferencesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">通用</p></body></html>"))
        self.uiserverPreferencesAction.setStatusTip(_translate("MainWindow", "显示服务器相关设置"))
        self.serverPreferencesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">服务器</p></body></html>"))
        self.uiwiresharkPreferencesAction.setStatusTip(_translate("MainWindow", "显示抓包相关设置"))
        self.wiresharkPreferencesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">抓包</p></body></html>"))
        self.uivpcsPreferencesAction.setStatusTip(_translate("MainWindow", "显示VPCS相关设置"))
        self.vpcsPreferencesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">VPCS</p></body></html>"))
        self.uidynamipsPreferencesAction.setStatusTip(_translate("MainWindow", "显示Dynamips设置"))
        self.dynamipsPreferencesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">模拟器</p></body></html>"))
        self.uiunixPreferencesAction.setStatusTip(_translate("MainWindow", "显示IOS on UNIX设置"))
        self.unixPreferencesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Unix</p></body></html>"))
        self.uivmwarePreferencesAction.setStatusTip(_translate("MainWindow", "显示VMware设置"))
        self.vmwarePreferencesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">VM</p></body></html>"))
        self.uirouterPreferencesAction.setStatusTip(_translate("MainWindow", "显示路由器相关设置"))
        self.routerPreferencesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">路由器</p></body></html>"))
        self.uiiouPreferencesAction.setStatusTip(_translate("MainWindow", "显示IOU设置"))
        self.iouPreferencesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">IOU</p></body></html>"))
        self.uihospitalPreferencesAction.setStatusTip(_translate("MainWindow", "显示医院信息系统相关设置"))
        self.hospitalPreferencesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">医用</p></body></html>"))
        self.menutab.setTabText(self.menutab.indexOf(self.tab_3), _translate("MainWindow", "设置"))
        self.uiStartAllAction.setStatusTip(_translate("MainWindow", "运行设备"))
        self.StartAllAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">运行</p></body></html>"))
        self.uiSuspendAllAction.setStatusTip(_translate("MainWindow", "暂停设备"))
        self.SuspendAllAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">暂停</p></body></html>"))
        self.uiStopAllAction.setStatusTip(_translate("MainWindow", "终止设备"))
        self.StopAllAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">终止</p></body></html>"))
        self.uiReloadAllAction.setStatusTip(_translate("MainWindow", "重启设备"))
        self.ReloadAllAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">重启</p></body></html>"))
        self.uiAddLinkAction.setStatusTip(_translate("MainWindow", "添加连接线"))
        self.AddLinkAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">连接</p></body></html>"))
        self.uiShowPortNamesAction.setStatusTip(_translate("MainWindow", "显示接口号"))
        self.ShowPortNamesAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">接口</p></body></html>"))
        self.uiConfigAllAction.setStatusTip(_translate("MainWindow", "配置设备"))
        self.ConfigAllAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">配置</p></body></html>"))
        self.uiZoomInAction.setStatusTip(_translate("MainWindow", "放大视图"))
        self.ZoomInAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">放大</p></body></html>"))
        self.uiZoomOutAction.setStatusTip(_translate("MainWindow", "缩小视图"))
        self.ZoomOutAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">缩小</p></body></html>"))
        self.uiScreenshotAction.setStatusTip(_translate("MainWindow", "屏幕截取"))
        self.ScreenshotAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">截屏</p></body></html>"))
        self.uiShowLayersAction.setStatusTip(_translate("MainWindow", "显示层次"))
        self.uiShowLayersAction.setText(_translate("MainWindow", "层次"))
        self.uiShowGridAction.setStatusTip(_translate("MainWindow", "显示网格"))
        self.uiShowGridAction.setText(_translate("MainWindow", "网格"))
        self.uiSnapToGridAction.setStatusTip(_translate("MainWindow", "对齐网格"))
        self.uiSnapToGridAction.setText(_translate("MainWindow", "对齐网格"))
        self.uiInsertImageAction.setStatusTip(_translate("MainWindow", "插入图片"))
        self.InsertImageAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">图片</p></body></html>"))
        self.uiAddNoteAction.setStatusTip(_translate("MainWindow", "添加标签"))
        self.AddNoteAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">标签</p></body></html>"))
        self.uiDrawEllipseAction.setStatusTip(_translate("MainWindow", "添加圆形"))
        self.DrawEllipseAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">圆形</p></body></html>"))
        self.uiDrawRectangleAction.setStatusTip(_translate("MainWindow", "添加矩形"))
        self.DrawRectangleAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">矩形</p></body></html>"))
        self.uiShowTopology.setText(_translate("MainWindow", "拓扑汇总   "))
        self.uiShowServer.setText(_translate("MainWindow", "服务器状态 "))
        self.menutab.setTabText(self.menutab.indexOf(self.tab_2), _translate("MainWindow", "工作台"))
        self.uiWareAction.setStatusTip(_translate("MainWindow", "打开MNSSware链接"))
        self.WareAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ware</p></body></html>"))
        self.uiExamAction.setStatusTip(_translate("MainWindow", "打开MNSSexam链接"))
        self.ExamAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">exam</p></body></html>"))
        self.uiStorageAction.setStatusTip(_translate("MainWindow", "打开MNSSstorage链接"))
        self.StorageAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">storage</p></body></html>"))
        self.uiPaperAction.setStatusTip(_translate("MainWindow", "打开MNSSpaper链接"))
        self.PaperAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">paper</p></body></html>"))
        self.uiToolsAction.setStatusTip(_translate("MainWindow", "打开MNSStools链接"))
        self.ToolsAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">tools</p></body></html>"))
        self.uiiMNSSAction.setStatusTip(_translate("MainWindow", "打开iMNSS门户首页"))
        self.iMNSSAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">iMNSS</p></body></html>"))
        self.menutab.setTabText(self.menutab.indexOf(self.tab_4), _translate("MainWindow", "成员"))
        self.uiCheckForUpdateAction.setStatusTip(_translate("MainWindow", "更新软件"))
        self.CheckForUpdateAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">更新</p></body></html>"))
        self.uiOnlineHelpAction.setStatusTip(_translate("MainWindow", "显示官网"))
        self.OnlineHelpAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">官网</p></body></html>"))
        self.uiExportDebugInformationAction.setStatusTip(_translate("MainWindow", "输出DeBug信息"))
        self.ExportDebugInformationAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">DeBug</p></body></html>"))
        self.uiDoctorAction.setStatusTip(_translate("MainWindow", "显示诊断信息"))
        self.DoctorAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">诊断</p></body></html>"))
        self.uiAboutAction.setStatusTip(_translate("MainWindow", "关于我们"))
        self.AboutAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">关于</p></body></html>"))
        self.uiGuideAction.setStatusTip(_translate("MainWindow", "医院信息系统导入向导"))
        self.GuideAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">向导</p></body></html>"))
        self.uiFeedbackAction.setStatusTip(_translate("MainWindow", "意见反馈"))
        self.FeedbackAction.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">反馈</p></body></html>"))
        self.menutab.setTabText(self.menutab.indexOf(self.tab_5), _translate("MainWindow", "帮助"))
        self.internetlable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">网络</p></body></html>"))
        self.uiBrowseRoutersAction.setStatusTip(_translate("MainWindow", " 添加路由器"))
        self.uiBrowseSwitchesAction.setStatusTip(_translate("MainWindow", "添加交换机"))
        self.uiBrowseSecurityDevicesAction.setStatusTip(_translate("MainWindow", "添加安全设备"))
        self.teiminallable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">系统</p></body></html>"))
        self.uiBrowseClientDevicesAction.setStatusTip(_translate("MainWindow", "添加客户端设备"))
        self.uiBrowseServerDevicesAction.setStatusTip(_translate("MainWindow", "添加服务器设备"))
        self.uiBrowseHISDevicesAction.setStatusTip(_translate("MainWindow", "添加HIS系统"))
        self.uiBrowseLISDevicesAction.setStatusTip(_translate("MainWindow", "添加LIS系统"))
        self.uiBrowsePACSDevicesAction.setStatusTip(_translate("MainWindow", "添加PACS系统"))
        self.connection.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">桥接</p></body></html>"))
        self.uiBrowseConnectDevicesAction.setStatusTip(_translate("MainWindow", "桥接到真实设备"))
        self.uiNodesDockWidget.setWindowTitle(_translate("MainWindow", "节点类型"))
        self.uiNodesView.setToolTip(_translate("MainWindow", "拖动一个节点到工作区（在拖动时按住Shift以添加多个相同的节点"))
        self.uiNodesView.headerItem().setText(0, _translate("MainWindow", "1"))
        self.uiTopologySummaryDockWidget.setWindowTitle(_translate("MainWindow", "拓扑汇总"))
        self.uiTopologySummaryTreeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        self.uiServerSummaryDockWidget.setWindowTitle(_translate("MainWindow", "服务器状态"))
        self.showtab.setTabText(self.showtab.indexOf(self.tab_6), _translate("MainWindow", "控制台"))
        self.showtab.setTabText(self.showtab.indexOf(self.tab_7), _translate("MainWindow", "下载列表"))

from ..console_view import ConsoleView
from ..graphics_view import GraphicsView
from ..nodes_view import NodesView
from ..server_summary_view import ServerSummaryView
from ..topology_summary_view import TopologySummaryView
from .import resources_rc
