# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(984, 715)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setStyleSheet("#toolBar_Devices QToolButton {\n"
"width: 50px;\n"
"height: 55px;\n"
"border:solid 1px black opacity 0.4;\n"
"background-none;\n"
"}\n"
"\n"
"#toolBar_General QToolButton {\n"
"width: 36px;\n"
"height: 36px;\n"
"border:solid 1px black opacity 0.4;\n"
"background-none;\n"
"}\n"
"\n"
"")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.uiCentralWidget = QtWidgets.QWidget(MainWindow)
        self.uiCentralWidget.setObjectName("uiCentralWidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.uiCentralWidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_4.addLayout(self.horizontalLayout_14)
        self.pushButton_3 = QtWidgets.QPushButton(self.uiCentralWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_3.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_3.setStyleSheet("border-image: url(:/images/MNSS.ico);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.uiCentralWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 8)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.uiCentralWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(32, 22))
        self.pushButton_4.setMaximumSize(QtCore.QSize(32, 22))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/minimum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 22))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_9 = QtWidgets.QPushButton(self.uiCentralWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(32, 22))
        self.pushButton_9.setMaximumSize(QtCore.QSize(32, 22))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.pushButton_9.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/restoredown.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/icons/maximization.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(32, 22))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_2 = QtWidgets.QPushButton(self.uiCentralWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 22))
        self.pushButton_2.setMaximumSize(QtCore.QSize(40, 22))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/close1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 22))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tabWidget = QtWidgets.QTabWidget(self.uiCentralWidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 108))
        self.tabWidget.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color: white;\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: rgb(240,240,240);\n"
"    border-style: inset;\n"
"    }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.uiNewProjectAction = QtWidgets.QPushButton(self.tab)
        self.uiNewProjectAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiNewProjectAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiNewProjectAction.setToolTip("")
        self.uiNewProjectAction.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiNewProjectAction.setIcon(icon3)
        self.uiNewProjectAction.setIconSize(QtCore.QSize(25, 25))
        self.uiNewProjectAction.setObjectName("uiNewProjectAction")
        self.verticalLayout_11.addWidget(self.uiNewProjectAction)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setMinimumSize(QtCore.QSize(30, 14))
        self.label_8.setMaximumSize(QtCore.QSize(30, 14))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.uiOpenProjectAction = QtWidgets.QPushButton(self.tab)
        self.uiOpenProjectAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiOpenProjectAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiOpenProjectAction.setToolTip("")
        self.uiOpenProjectAction.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/classic_icons/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiOpenProjectAction.setIcon(icon4)
        self.uiOpenProjectAction.setIconSize(QtCore.QSize(25, 25))
        self.uiOpenProjectAction.setObjectName("uiOpenProjectAction")
        self.verticalLayout_23.addWidget(self.uiOpenProjectAction)
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setMinimumSize(QtCore.QSize(30, 14))
        self.label_20.setMaximumSize(QtCore.QSize(30, 14))
        self.label_20.setObjectName("label_20")
        self.verticalLayout_23.addWidget(self.label_20)
        self.horizontalLayout_5.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.uiSaveProjectAction = QtWidgets.QPushButton(self.tab)
        self.uiSaveProjectAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiSaveProjectAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiSaveProjectAction.setToolTip("")
        self.uiSaveProjectAction.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSaveProjectAction.setIcon(icon5)
        self.uiSaveProjectAction.setIconSize(QtCore.QSize(25, 25))
        self.uiSaveProjectAction.setObjectName("uiSaveProjectAction")
        self.verticalLayout_24.addWidget(self.uiSaveProjectAction)
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setMinimumSize(QtCore.QSize(30, 14))
        self.label_21.setMaximumSize(QtCore.QSize(30, 14))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_24.addWidget(self.label_21)
        self.horizontalLayout_5.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.uiSaveProjectAsAction = QtWidgets.QPushButton(self.tab)
        self.uiSaveProjectAsAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiSaveProjectAsAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiSaveProjectAsAction.setToolTip("")
        self.uiSaveProjectAsAction.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/saveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSaveProjectAsAction.setIcon(icon6)
        self.uiSaveProjectAsAction.setIconSize(QtCore.QSize(25, 25))
        self.uiSaveProjectAsAction.setObjectName("uiSaveProjectAsAction")
        self.verticalLayout_25.addWidget(self.uiSaveProjectAsAction)
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setMinimumSize(QtCore.QSize(30, 14))
        self.label_22.setMaximumSize(QtCore.QSize(30, 14))
        self.label_22.setObjectName("label_22")
        self.verticalLayout_25.addWidget(self.label_22)
        self.horizontalLayout_5.addLayout(self.verticalLayout_25)
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.uiImportProjectAction = QtWidgets.QPushButton(self.tab)
        self.uiImportProjectAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiImportProjectAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiImportProjectAction.setToolTip("")
        self.uiImportProjectAction.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiImportProjectAction.setIcon(icon7)
        self.uiImportProjectAction.setIconSize(QtCore.QSize(25, 25))
        self.uiImportProjectAction.setObjectName("uiImportProjectAction")
        self.verticalLayout_26.addWidget(self.uiImportProjectAction)
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setMinimumSize(QtCore.QSize(30, 14))
        self.label_23.setMaximumSize(QtCore.QSize(30, 14))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_26.addWidget(self.label_23)
        self.horizontalLayout_5.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.uiExportProjectAction = QtWidgets.QPushButton(self.tab)
        self.uiExportProjectAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiExportProjectAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiExportProjectAction.setToolTip("")
        self.uiExportProjectAction.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiExportProjectAction.setIcon(icon8)
        self.uiExportProjectAction.setIconSize(QtCore.QSize(25, 25))
        self.uiExportProjectAction.setObjectName("uiExportProjectAction")
        self.verticalLayout_27.addWidget(self.uiExportProjectAction)
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setMinimumSize(QtCore.QSize(30, 14))
        self.label_24.setMaximumSize(QtCore.QSize(30, 14))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_27.addWidget(self.label_24)
        self.horizontalLayout_5.addLayout(self.verticalLayout_27)
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_5.addWidget(self.line_5)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab)
        self.pushButton_28.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_28.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_28.setToolTip("")
        self.pushButton_28.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_28.setIcon(icon9)
        self.pushButton_28.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_29.addWidget(self.pushButton_28)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setMinimumSize(QtCore.QSize(30, 14))
        self.label_26.setMaximumSize(QtCore.QSize(30, 14))
        self.label_26.setObjectName("label_26")
        self.verticalLayout_29.addWidget(self.label_26)
        self.horizontalLayout_5.addLayout(self.verticalLayout_29)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.pushButton_30 = QtWidgets.QPushButton(self.tab)
        self.pushButton_30.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_30.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_30.setToolTip("")
        self.pushButton_30.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_30.setIcon(icon10)
        self.pushButton_30.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_31.addWidget(self.pushButton_30)
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setMinimumSize(QtCore.QSize(30, 14))
        self.label_28.setMaximumSize(QtCore.QSize(30, 14))
        self.label_28.setObjectName("label_28")
        self.verticalLayout_31.addWidget(self.label_28)
        self.horizontalLayout_5.addLayout(self.verticalLayout_31)
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_5.addWidget(self.line_6)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.uiQuitAction = QtWidgets.QPushButton(self.tab)
        self.uiQuitAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiQuitAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiQuitAction.setToolTip("")
        self.uiQuitAction.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiQuitAction.setIcon(icon11)
        self.uiQuitAction.setIconSize(QtCore.QSize(25, 25))
        self.uiQuitAction.setObjectName("uiQuitAction")
        self.verticalLayout_28.addWidget(self.uiQuitAction)
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setMinimumSize(QtCore.QSize(30, 14))
        self.label_25.setMaximumSize(QtCore.QSize(30, 14))
        self.label_25.setObjectName("label_25")
        self.verticalLayout_28.addWidget(self.label_25)
        self.horizontalLayout_5.addLayout(self.verticalLayout_28)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.uiPreferencesAction = QtWidgets.QPushButton(self.tab_3)
        self.uiPreferencesAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiPreferencesAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiPreferencesAction.setToolTip("")
        self.uiPreferencesAction.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPreferencesAction.setIcon(icon12)
        self.uiPreferencesAction.setIconSize(QtCore.QSize(30, 30))
        self.uiPreferencesAction.setObjectName("uiPreferencesAction")
        self.verticalLayout_53.addWidget(self.uiPreferencesAction)
        self.label_48 = QtWidgets.QLabel(self.tab_3)
        self.label_48.setMinimumSize(QtCore.QSize(40, 14))
        self.label_48.setMaximumSize(QtCore.QSize(40, 14))
        self.label_48.setObjectName("label_48")
        self.verticalLayout_53.addWidget(self.label_48)
        self.horizontalLayout_9.addLayout(self.verticalLayout_53)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setToolTip("")
        self.pushButton_5.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/server.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon13)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_49.addWidget(self.pushButton_5)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setMinimumSize(QtCore.QSize(40, 14))
        self.label_5.setMaximumSize(QtCore.QSize(40, 14))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_49.addWidget(self.label_5)
        self.horizontalLayout_9.addLayout(self.verticalLayout_49)
        self.verticalLayout_54 = QtWidgets.QVBoxLayout()
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.pushButton_49 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_49.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_49.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_49.setToolTip("")
        self.pushButton_49.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/wireshark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_49.setIcon(icon14)
        self.pushButton_49.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_49.setObjectName("pushButton_49")
        self.verticalLayout_54.addWidget(self.pushButton_49)
        self.label_49 = QtWidgets.QLabel(self.tab_3)
        self.label_49.setMinimumSize(QtCore.QSize(40, 14))
        self.label_49.setMaximumSize(QtCore.QSize(40, 14))
        self.label_49.setObjectName("label_49")
        self.verticalLayout_54.addWidget(self.label_49)
        self.horizontalLayout_9.addLayout(self.verticalLayout_54)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setToolTip("")
        self.pushButton_7.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/vpcsshezhi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon15)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_51.addWidget(self.pushButton_7)
        self.label_46 = QtWidgets.QLabel(self.tab_3)
        self.label_46.setMinimumSize(QtCore.QSize(40, 14))
        self.label_46.setMaximumSize(QtCore.QSize(40, 14))
        self.label_46.setObjectName("label_46")
        self.verticalLayout_51.addWidget(self.label_46)
        self.horizontalLayout_9.addLayout(self.verticalLayout_51)
        self.verticalLayout_66 = QtWidgets.QVBoxLayout()
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.uiDynamipsAction = QtWidgets.QPushButton(self.tab_3)
        self.uiDynamipsAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiDynamipsAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiDynamipsAction.setToolTip("")
        self.uiDynamipsAction.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/images/dynamips.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiDynamipsAction.setIcon(icon16)
        self.uiDynamipsAction.setIconSize(QtCore.QSize(30, 30))
        self.uiDynamipsAction.setObjectName("uiDynamipsAction")
        self.verticalLayout_66.addWidget(self.uiDynamipsAction)
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        self.label_60.setMinimumSize(QtCore.QSize(40, 14))
        self.label_60.setMaximumSize(QtCore.QSize(40, 14))
        self.label_60.setObjectName("label_60")
        self.verticalLayout_66.addWidget(self.label_60)
        self.horizontalLayout_9.addLayout(self.verticalLayout_66)
        self.verticalLayout_65 = QtWidgets.QVBoxLayout()
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.uifUnixAction = QtWidgets.QPushButton(self.tab_3)
        self.uifUnixAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uifUnixAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uifUnixAction.setToolTip("")
        self.uifUnixAction.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/images/unix.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uifUnixAction.setIcon(icon17)
        self.uifUnixAction.setIconSize(QtCore.QSize(30, 30))
        self.uifUnixAction.setObjectName("uifUnixAction")
        self.verticalLayout_65.addWidget(self.uifUnixAction)
        self.label_59 = QtWidgets.QLabel(self.tab_3)
        self.label_59.setMinimumSize(QtCore.QSize(40, 14))
        self.label_59.setMaximumSize(QtCore.QSize(40, 14))
        self.label_59.setObjectName("label_59")
        self.verticalLayout_65.addWidget(self.label_59)
        self.horizontalLayout_9.addLayout(self.verticalLayout_65)
        self.verticalLayout_64 = QtWidgets.QVBoxLayout()
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.uiVMAction = QtWidgets.QPushButton(self.tab_3)
        self.uiVMAction.setMinimumSize(QtCore.QSize(40, 40))
        self.uiVMAction.setMaximumSize(QtCore.QSize(40, 40))
        self.uiVMAction.setToolTip("")
        self.uiVMAction.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/images/vmware.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiVMAction.setIcon(icon18)
        self.uiVMAction.setIconSize(QtCore.QSize(30, 30))
        self.uiVMAction.setObjectName("uiVMAction")
        self.verticalLayout_64.addWidget(self.uiVMAction)
        self.label_57 = QtWidgets.QLabel(self.tab_3)
        self.label_57.setMinimumSize(QtCore.QSize(40, 14))
        self.label_57.setMaximumSize(QtCore.QSize(40, 14))
        self.label_57.setObjectName("label_57")
        self.verticalLayout_64.addWidget(self.label_57)
        self.horizontalLayout_9.addLayout(self.verticalLayout_64)
        self.line_13 = QtWidgets.QFrame(self.tab_3)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_9.addWidget(self.line_13)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_6.setToolTip("")
        self.pushButton_6.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/router.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon19)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_50.addWidget(self.pushButton_6)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setMinimumSize(QtCore.QSize(40, 14))
        self.label_6.setMaximumSize(QtCore.QSize(40, 14))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_50.addWidget(self.label_6)
        self.horizontalLayout_9.addLayout(self.verticalLayout_50)
        self.verticalLayout_67 = QtWidgets.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.UiIOUAction = QtWidgets.QPushButton(self.tab_3)
        self.UiIOUAction.setMinimumSize(QtCore.QSize(40, 40))
        self.UiIOUAction.setMaximumSize(QtCore.QSize(40, 40))
        self.UiIOUAction.setToolTip("")
        self.UiIOUAction.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/images/IOU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UiIOUAction.setIcon(icon20)
        self.UiIOUAction.setIconSize(QtCore.QSize(30, 30))
        self.UiIOUAction.setObjectName("UiIOUAction")
        self.verticalLayout_67.addWidget(self.UiIOUAction)
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        self.label_61.setMinimumSize(QtCore.QSize(40, 14))
        self.label_61.setMaximumSize(QtCore.QSize(40, 14))
        self.label_61.setObjectName("label_61")
        self.verticalLayout_67.addWidget(self.label_61)
        self.horizontalLayout_9.addLayout(self.verticalLayout_67)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setToolTip("")
        self.pushButton_8.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/hospital.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon21)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_52.addWidget(self.pushButton_8)
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        self.label_47.setMinimumSize(QtCore.QSize(40, 14))
        self.label_47.setMaximumSize(QtCore.QSize(40, 14))
        self.label_47.setObjectName("label_47")
        self.verticalLayout_52.addWidget(self.label_47)
        self.horizontalLayout_9.addLayout(self.verticalLayout_52)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.uiStartAllAction = QtWidgets.QPushButton(self.tab_2)
        self.uiStartAllAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiStartAllAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiStartAllAction.setToolTip("")
        self.uiStartAllAction.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/charcoal_icons/start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon22.addPixmap(QtGui.QPixmap(":/classic_icons/start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon22.addPixmap(QtGui.QPixmap(":/classic_icons/start.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.uiStartAllAction.setIcon(icon22)
        self.uiStartAllAction.setIconSize(QtCore.QSize(25, 25))
        self.uiStartAllAction.setObjectName("uiStartAllAction")
        self.verticalLayout_10.addWidget(self.uiStartAllAction)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setMinimumSize(QtCore.QSize(30, 14))
        self.label_7.setMaximumSize(QtCore.QSize(30, 14))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.uiSuspendAllAction = QtWidgets.QPushButton(self.tab_2)
        self.uiSuspendAllAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiSuspendAllAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiSuspendAllAction.setToolTip("")
        self.uiSuspendAllAction.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/classic_icons/pause.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon23.addPixmap(QtGui.QPixmap(":/classic_icons/pause.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon23.addPixmap(QtGui.QPixmap(":/classic_icons/pause.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.uiSuspendAllAction.setIcon(icon23)
        self.uiSuspendAllAction.setIconSize(QtCore.QSize(25, 25))
        self.uiSuspendAllAction.setObjectName("uiSuspendAllAction")
        self.verticalLayout_33.addWidget(self.uiSuspendAllAction)
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setMinimumSize(QtCore.QSize(30, 14))
        self.label_30.setMaximumSize(QtCore.QSize(30, 14))
        self.label_30.setObjectName("label_30")
        self.verticalLayout_33.addWidget(self.label_30)
        self.horizontalLayout_7.addLayout(self.verticalLayout_33)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.uiStopAllAction = QtWidgets.QPushButton(self.tab_2)
        self.uiStopAllAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiStopAllAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiStopAllAction.setToolTip("")
        self.uiStopAllAction.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/classic_icons/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon24.addPixmap(QtGui.QPixmap(":/classic_icons/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon24.addPixmap(QtGui.QPixmap(":/classic_icons/stop.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.uiStopAllAction.setIcon(icon24)
        self.uiStopAllAction.setIconSize(QtCore.QSize(25, 25))
        self.uiStopAllAction.setObjectName("uiStopAllAction")
        self.verticalLayout_34.addWidget(self.uiStopAllAction)
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setMinimumSize(QtCore.QSize(30, 14))
        self.label_31.setMaximumSize(QtCore.QSize(30, 14))
        self.label_31.setObjectName("label_31")
        self.verticalLayout_34.addWidget(self.label_31)
        self.horizontalLayout_7.addLayout(self.verticalLayout_34)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.uiReloadAllAction = QtWidgets.QPushButton(self.tab_2)
        self.uiReloadAllAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiReloadAllAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiReloadAllAction.setToolTip("")
        self.uiReloadAllAction.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/classic_icons/reload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiReloadAllAction.setIcon(icon25)
        self.uiReloadAllAction.setIconSize(QtCore.QSize(25, 25))
        self.uiReloadAllAction.setObjectName("uiReloadAllAction")
        self.verticalLayout_32.addWidget(self.uiReloadAllAction)
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setMinimumSize(QtCore.QSize(30, 14))
        self.label_29.setMaximumSize(QtCore.QSize(30, 14))
        self.label_29.setObjectName("label_29")
        self.verticalLayout_32.addWidget(self.label_29)
        self.horizontalLayout_7.addLayout(self.verticalLayout_32)
        self.verticalLayout_63 = QtWidgets.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.uiAddLinkAction = QtWidgets.QPushButton(self.tab_2)
        self.uiAddLinkAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiAddLinkAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiAddLinkAction.setToolTip("")
        self.uiAddLinkAction.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/classic_icons/add-link-cancel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon26.addPixmap(QtGui.QPixmap(":/classic_icons/add-link.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon26.addPixmap(QtGui.QPixmap(":/classic_icons/add-link-cancel.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.uiAddLinkAction.setIcon(icon26)
        self.uiAddLinkAction.setIconSize(QtCore.QSize(25, 25))
        self.uiAddLinkAction.setObjectName("uiAddLinkAction")
        self.verticalLayout_63.addWidget(self.uiAddLinkAction)
        self.label_58 = QtWidgets.QLabel(self.tab_2)
        self.label_58.setMinimumSize(QtCore.QSize(30, 14))
        self.label_58.setMaximumSize(QtCore.QSize(30, 14))
        self.label_58.setObjectName("label_58")
        self.verticalLayout_63.addWidget(self.label_58)
        self.horizontalLayout_7.addLayout(self.verticalLayout_63)
        self.line_12 = QtWidgets.QFrame(self.tab_2)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_7.addWidget(self.line_12)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.uiShowPortNamesAction = QtWidgets.QPushButton(self.tab_2)
        self.uiShowPortNamesAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiShowPortNamesAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiShowPortNamesAction.setToolTip("")
        self.uiShowPortNamesAction.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/classic_icons/show-interface-names-hover.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon27.addPixmap(QtGui.QPixmap(":/classic_icons/show-interface-names.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon27.addPixmap(QtGui.QPixmap(":/classic_icons/show-interface-names-hover.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.uiShowPortNamesAction.setIcon(icon27)
        self.uiShowPortNamesAction.setIconSize(QtCore.QSize(25, 25))
        self.uiShowPortNamesAction.setObjectName("uiShowPortNamesAction")
        self.verticalLayout_40.addWidget(self.uiShowPortNamesAction)
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        self.label_37.setMinimumSize(QtCore.QSize(30, 14))
        self.label_37.setMaximumSize(QtCore.QSize(30, 14))
        self.label_37.setObjectName("label_37")
        self.verticalLayout_40.addWidget(self.label_37)
        self.horizontalLayout_7.addLayout(self.verticalLayout_40)
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.uiConsoleAllAction = QtWidgets.QPushButton(self.tab_2)
        self.uiConsoleAllAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiConsoleAllAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiConsoleAllAction.setToolTip("")
        self.uiConsoleAllAction.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/classic_icons/console.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiConsoleAllAction.setIcon(icon28)
        self.uiConsoleAllAction.setIconSize(QtCore.QSize(25, 25))
        self.uiConsoleAllAction.setObjectName("uiConsoleAllAction")
        self.verticalLayout_41.addWidget(self.uiConsoleAllAction)
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setMinimumSize(QtCore.QSize(30, 14))
        self.label_38.setMaximumSize(QtCore.QSize(30, 14))
        self.label_38.setObjectName("label_38")
        self.verticalLayout_41.addWidget(self.label_38)
        self.horizontalLayout_7.addLayout(self.verticalLayout_41)
        self.line_7 = QtWidgets.QFrame(self.tab_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_7.addWidget(self.line_7)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.uiZoomInAction = QtWidgets.QPushButton(self.tab_2)
        self.uiZoomInAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiZoomInAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiZoomInAction.setToolTip("")
        self.uiZoomInAction.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/classic_icons/zoom-in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiZoomInAction.setIcon(icon29)
        self.uiZoomInAction.setIconSize(QtCore.QSize(25, 25))
        self.uiZoomInAction.setObjectName("uiZoomInAction")
        self.verticalLayout_30.addWidget(self.uiZoomInAction)
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setMinimumSize(QtCore.QSize(30, 14))
        self.label_27.setMaximumSize(QtCore.QSize(30, 14))
        self.label_27.setObjectName("label_27")
        self.verticalLayout_30.addWidget(self.label_27)
        self.horizontalLayout_7.addLayout(self.verticalLayout_30)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.uiZoomOutAction = QtWidgets.QPushButton(self.tab_2)
        self.uiZoomOutAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiZoomOutAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiZoomOutAction.setToolTip("")
        self.uiZoomOutAction.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/classic_icons/zoom-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiZoomOutAction.setIcon(icon30)
        self.uiZoomOutAction.setIconSize(QtCore.QSize(25, 25))
        self.uiZoomOutAction.setObjectName("uiZoomOutAction")
        self.verticalLayout_35.addWidget(self.uiZoomOutAction)
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setMinimumSize(QtCore.QSize(30, 14))
        self.label_32.setMaximumSize(QtCore.QSize(30, 14))
        self.label_32.setObjectName("label_32")
        self.verticalLayout_35.addWidget(self.label_32)
        self.horizontalLayout_7.addLayout(self.verticalLayout_35)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.uiScreenshotAction = QtWidgets.QPushButton(self.tab_2)
        self.uiScreenshotAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiScreenshotAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiScreenshotAction.setToolTip("")
        self.uiScreenshotAction.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/classic_icons/camera-photo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiScreenshotAction.setIcon(icon31)
        self.uiScreenshotAction.setIconSize(QtCore.QSize(25, 25))
        self.uiScreenshotAction.setObjectName("uiScreenshotAction")
        self.verticalLayout_42.addWidget(self.uiScreenshotAction)
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setMinimumSize(QtCore.QSize(30, 14))
        self.label_39.setMaximumSize(QtCore.QSize(30, 14))
        self.label_39.setObjectName("label_39")
        self.verticalLayout_42.addWidget(self.label_39)
        self.horizontalLayout_7.addLayout(self.verticalLayout_42)
        self.line_8 = QtWidgets.QFrame(self.tab_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_7.addWidget(self.line_8)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.uiShowLayersAction = QtWidgets.QCheckBox(self.tab_2)
        self.uiShowLayersAction.setMinimumSize(QtCore.QSize(71, 16))
        self.uiShowLayersAction.setMaximumSize(QtCore.QSize(71, 16))
        self.uiShowLayersAction.setToolTip("")
        self.uiShowLayersAction.setObjectName("uiShowLayersAction")
        self.verticalLayout_8.addWidget(self.uiShowLayersAction)
        self.uiShowGridAction = QtWidgets.QCheckBox(self.tab_2)
        self.uiShowGridAction.setMinimumSize(QtCore.QSize(71, 16))
        self.uiShowGridAction.setMaximumSize(QtCore.QSize(71, 16))
        self.uiShowGridAction.setToolTip("")
        self.uiShowGridAction.setObjectName("uiShowGridAction")
        self.verticalLayout_8.addWidget(self.uiShowGridAction)
        self.uiSnapToGridAction = QtWidgets.QCheckBox(self.tab_2)
        self.uiSnapToGridAction.setMinimumSize(QtCore.QSize(85, 16))
        self.uiSnapToGridAction.setMaximumSize(QtCore.QSize(71, 16))
        self.uiSnapToGridAction.setToolTip("")
        self.uiSnapToGridAction.setObjectName("uiSnapToGridAction")
        self.verticalLayout_8.addWidget(self.uiSnapToGridAction)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.line_9 = QtWidgets.QFrame(self.tab_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_7.addWidget(self.line_9)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.uiInsertImageAction = QtWidgets.QPushButton(self.tab_2)
        self.uiInsertImageAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiInsertImageAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiInsertImageAction.setToolTip("")
        self.uiInsertImageAction.setText("")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/classic_icons/image.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiInsertImageAction.setIcon(icon32)
        self.uiInsertImageAction.setIconSize(QtCore.QSize(25, 25))
        self.uiInsertImageAction.setObjectName("uiInsertImageAction")
        self.verticalLayout_37.addWidget(self.uiInsertImageAction)
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setMinimumSize(QtCore.QSize(30, 14))
        self.label_34.setMaximumSize(QtCore.QSize(30, 14))
        self.label_34.setObjectName("label_34")
        self.verticalLayout_37.addWidget(self.label_34)
        self.horizontalLayout_7.addLayout(self.verticalLayout_37)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.uiAddNoteAction = QtWidgets.QPushButton(self.tab_2)
        self.uiAddNoteAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiAddNoteAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiAddNoteAction.setToolTip("")
        self.uiAddNoteAction.setText("")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/classic_icons/add-note.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAddNoteAction.setIcon(icon33)
        self.uiAddNoteAction.setIconSize(QtCore.QSize(25, 25))
        self.uiAddNoteAction.setObjectName("uiAddNoteAction")
        self.verticalLayout_36.addWidget(self.uiAddNoteAction)
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setMinimumSize(QtCore.QSize(30, 14))
        self.label_33.setMaximumSize(QtCore.QSize(30, 14))
        self.label_33.setObjectName("label_33")
        self.verticalLayout_36.addWidget(self.label_33)
        self.horizontalLayout_7.addLayout(self.verticalLayout_36)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.uiDrawEllipseAction = QtWidgets.QPushButton(self.tab_2)
        self.uiDrawEllipseAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiDrawEllipseAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiDrawEllipseAction.setToolTip("")
        self.uiDrawEllipseAction.setText("")
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/classic_icons/ellipse.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiDrawEllipseAction.setIcon(icon34)
        self.uiDrawEllipseAction.setIconSize(QtCore.QSize(25, 25))
        self.uiDrawEllipseAction.setObjectName("uiDrawEllipseAction")
        self.verticalLayout_38.addWidget(self.uiDrawEllipseAction)
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setMinimumSize(QtCore.QSize(30, 14))
        self.label_35.setMaximumSize(QtCore.QSize(30, 14))
        self.label_35.setObjectName("label_35")
        self.verticalLayout_38.addWidget(self.label_35)
        self.horizontalLayout_7.addLayout(self.verticalLayout_38)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.uiDrawRectangleAction = QtWidgets.QPushButton(self.tab_2)
        self.uiDrawRectangleAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiDrawRectangleAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiDrawRectangleAction.setToolTip("")
        self.uiDrawRectangleAction.setText("")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/classic_icons/rectangle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiDrawRectangleAction.setIcon(icon35)
        self.uiDrawRectangleAction.setIconSize(QtCore.QSize(25, 25))
        self.uiDrawRectangleAction.setObjectName("uiDrawRectangleAction")
        self.verticalLayout_39.addWidget(self.uiDrawRectangleAction)
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setMinimumSize(QtCore.QSize(30, 14))
        self.label_36.setMaximumSize(QtCore.QSize(30, 14))
        self.label_36.setObjectName("label_36")
        self.verticalLayout_39.addWidget(self.label_36)
        self.horizontalLayout_7.addLayout(self.verticalLayout_39)
        self.line_10 = QtWidgets.QFrame(self.tab_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_7.addWidget(self.line_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.uiShowTopology = QtWidgets.QCheckBox(self.tab_2)
        self.uiShowTopology.setMinimumSize(QtCore.QSize(100, 16))
        self.uiShowTopology.setMaximumSize(QtCore.QSize(100, 16))
        self.uiShowTopology.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.uiShowTopology.setObjectName("uiShowTopology")
        self.verticalLayout_9.addWidget(self.uiShowTopology)
        self.uiShowServer = QtWidgets.QCheckBox(self.tab_2)
        self.uiShowServer.setMinimumSize(QtCore.QSize(100, 16))
        self.uiShowServer.setMaximumSize(QtCore.QSize(100, 16))
        self.uiShowServer.setObjectName("uiShowServer")
        self.verticalLayout_9.addWidget(self.uiShowServer)
        self.uiShowConsole = QtWidgets.QCheckBox(self.tab_2)
        self.uiShowConsole.setMinimumSize(QtCore.QSize(100, 16))
        self.uiShowConsole.setMaximumSize(QtCore.QSize(100, 16))
        self.uiShowConsole.setObjectName("uiShowConsole")
        self.verticalLayout_9.addWidget(self.uiShowConsole)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.horizontalLayout_7.addLayout(self.verticalLayout_44)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.horizontalLayout_7.addLayout(self.verticalLayout_43)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout()
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.pushButton_50 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_50.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_50.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_50.setToolTip("")
        self.pushButton_50.setText("")
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/icons/security.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_50.setIcon(icon36)
        self.pushButton_50.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_50.setObjectName("pushButton_50")
        self.verticalLayout_55.addWidget(self.pushButton_50)
        self.label_50 = QtWidgets.QLabel(self.tab_4)
        self.label_50.setMinimumSize(QtCore.QSize(30, 14))
        self.label_50.setMaximumSize(QtCore.QSize(30, 14))
        self.label_50.setObjectName("label_50")
        self.verticalLayout_55.addWidget(self.label_50)
        self.horizontalLayout_11.addLayout(self.verticalLayout_55)
        self.verticalLayout_56 = QtWidgets.QVBoxLayout()
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.pushButton_51 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_51.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_51.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_51.setToolTip("")
        self.pushButton_51.setText("")
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/icons/hospitals.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_51.setIcon(icon37)
        self.pushButton_51.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_51.setObjectName("pushButton_51")
        self.verticalLayout_56.addWidget(self.pushButton_51)
        self.label_51 = QtWidgets.QLabel(self.tab_4)
        self.label_51.setMinimumSize(QtCore.QSize(30, 14))
        self.label_51.setMaximumSize(QtCore.QSize(30, 14))
        self.label_51.setObjectName("label_51")
        self.verticalLayout_56.addWidget(self.label_51)
        self.horizontalLayout_11.addLayout(self.verticalLayout_56)
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.pushButton_47 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_47.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_47.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_47.setToolTip("")
        self.pushButton_47.setText("")
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/icons/internet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_47.setIcon(icon38)
        self.pushButton_47.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_47.setObjectName("pushButton_47")
        self.verticalLayout_48.addWidget(self.pushButton_47)
        self.label_45 = QtWidgets.QLabel(self.tab_4)
        self.label_45.setMinimumSize(QtCore.QSize(30, 14))
        self.label_45.setMaximumSize(QtCore.QSize(30, 14))
        self.label_45.setObjectName("label_45")
        self.verticalLayout_48.addWidget(self.label_45)
        self.horizontalLayout_11.addLayout(self.verticalLayout_48)
        self.line_14 = QtWidgets.QFrame(self.tab_4)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayout_11.addWidget(self.line_14)
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.pushButton_52 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_52.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_52.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_52.setToolTip("")
        self.pushButton_52.setText("")
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/icons/example.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_52.setIcon(icon39)
        self.pushButton_52.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_52.setObjectName("pushButton_52")
        self.verticalLayout_57.addWidget(self.pushButton_52)
        self.label_52 = QtWidgets.QLabel(self.tab_4)
        self.label_52.setMinimumSize(QtCore.QSize(30, 14))
        self.label_52.setMaximumSize(QtCore.QSize(30, 14))
        self.label_52.setObjectName("label_52")
        self.verticalLayout_57.addWidget(self.label_52)
        self.horizontalLayout_11.addLayout(self.verticalLayout_57)
        self.line_15 = QtWidgets.QFrame(self.tab_4)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.horizontalLayout_11.addWidget(self.line_15)
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.pushButton_53 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_53.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_53.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_53.setToolTip("")
        self.pushButton_53.setText("")
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/icons/guide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_53.setIcon(icon40)
        self.pushButton_53.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_53.setObjectName("pushButton_53")
        self.verticalLayout_58.addWidget(self.pushButton_53)
        self.label_53 = QtWidgets.QLabel(self.tab_4)
        self.label_53.setMinimumSize(QtCore.QSize(30, 14))
        self.label_53.setMaximumSize(QtCore.QSize(30, 14))
        self.label_53.setObjectName("label_53")
        self.verticalLayout_58.addWidget(self.label_53)
        self.horizontalLayout_11.addLayout(self.verticalLayout_58)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout()
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.uiCheckForUpdateAction = QtWidgets.QPushButton(self.tab_5)
        self.uiCheckForUpdateAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiCheckForUpdateAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiCheckForUpdateAction.setToolTip("")
        self.uiCheckForUpdateAction.setText("")
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/icons/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCheckForUpdateAction.setIcon(icon41)
        self.uiCheckForUpdateAction.setIconSize(QtCore.QSize(25, 25))
        self.uiCheckForUpdateAction.setObjectName("uiCheckForUpdateAction")
        self.verticalLayout_61.addWidget(self.uiCheckForUpdateAction)
        self.label_56 = QtWidgets.QLabel(self.tab_5)
        self.label_56.setMinimumSize(QtCore.QSize(30, 14))
        self.label_56.setMaximumSize(QtCore.QSize(30, 14))
        self.label_56.setObjectName("label_56")
        self.verticalLayout_61.addWidget(self.label_56)
        self.horizontalLayout_15.addLayout(self.verticalLayout_61)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.uiOnlineHelpAction = QtWidgets.QPushButton(self.tab_5)
        self.uiOnlineHelpAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiOnlineHelpAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiOnlineHelpAction.setToolTip("")
        self.uiOnlineHelpAction.setText("")
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/icons/online.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiOnlineHelpAction.setIcon(icon42)
        self.uiOnlineHelpAction.setIconSize(QtCore.QSize(25, 25))
        self.uiOnlineHelpAction.setObjectName("uiOnlineHelpAction")
        self.verticalLayout_45.addWidget(self.uiOnlineHelpAction)
        self.label_42 = QtWidgets.QLabel(self.tab_5)
        self.label_42.setMinimumSize(QtCore.QSize(30, 14))
        self.label_42.setMaximumSize(QtCore.QSize(30, 14))
        self.label_42.setObjectName("label_42")
        self.verticalLayout_45.addWidget(self.label_42)
        self.horizontalLayout_15.addLayout(self.verticalLayout_45)
        self.verticalLayout_60 = QtWidgets.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.uiExportDebugInformationAction = QtWidgets.QPushButton(self.tab_5)
        self.uiExportDebugInformationAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiExportDebugInformationAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiExportDebugInformationAction.setText("")
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/icons/debugstepout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiExportDebugInformationAction.setIcon(icon43)
        self.uiExportDebugInformationAction.setIconSize(QtCore.QSize(25, 25))
        self.uiExportDebugInformationAction.setObjectName("uiExportDebugInformationAction")
        self.verticalLayout_60.addWidget(self.uiExportDebugInformationAction)
        self.label_55 = QtWidgets.QLabel(self.tab_5)
        self.label_55.setMinimumSize(QtCore.QSize(30, 14))
        self.label_55.setMaximumSize(QtCore.QSize(30, 14))
        self.label_55.setToolTip("")
        self.label_55.setObjectName("label_55")
        self.verticalLayout_60.addWidget(self.label_55)
        self.horizontalLayout_15.addLayout(self.verticalLayout_60)
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.uiDoctorAction = QtWidgets.QPushButton(self.tab_5)
        self.uiDoctorAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiDoctorAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiDoctorAction.setToolTip("")
        self.uiDoctorAction.setText("")
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(":/icons/doctorshezhi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiDoctorAction.setIcon(icon44)
        self.uiDoctorAction.setIconSize(QtCore.QSize(25, 25))
        self.uiDoctorAction.setObjectName("uiDoctorAction")
        self.verticalLayout_59.addWidget(self.uiDoctorAction)
        self.label_54 = QtWidgets.QLabel(self.tab_5)
        self.label_54.setMinimumSize(QtCore.QSize(30, 14))
        self.label_54.setMaximumSize(QtCore.QSize(30, 14))
        self.label_54.setObjectName("label_54")
        self.verticalLayout_59.addWidget(self.label_54)
        self.horizontalLayout_15.addLayout(self.verticalLayout_59)
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.uiAboutAction = QtWidgets.QPushButton(self.tab_5)
        self.uiAboutAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uiAboutAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uiAboutAction.setToolTip("")
        self.uiAboutAction.setText("")
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(":/icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAboutAction.setIcon(icon45)
        self.uiAboutAction.setIconSize(QtCore.QSize(25, 25))
        self.uiAboutAction.setObjectName("uiAboutAction")
        self.verticalLayout_46.addWidget(self.uiAboutAction)
        self.label_43 = QtWidgets.QLabel(self.tab_5)
        self.label_43.setMinimumSize(QtCore.QSize(30, 14))
        self.label_43.setMaximumSize(QtCore.QSize(30, 14))
        self.label_43.setObjectName("label_43")
        self.verticalLayout_46.addWidget(self.label_43)
        self.horizontalLayout_15.addLayout(self.verticalLayout_46)
        self.line_11 = QtWidgets.QFrame(self.tab_5)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_15.addWidget(self.line_11)
        self.verticalLayout_62 = QtWidgets.QVBoxLayout()
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.uifeedbackAction = QtWidgets.QPushButton(self.tab_5)
        self.uifeedbackAction.setMinimumSize(QtCore.QSize(30, 30))
        self.uifeedbackAction.setMaximumSize(QtCore.QSize(30, 30))
        self.uifeedbackAction.setToolTip("")
        self.uifeedbackAction.setText("")
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(":/images/feedback.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uifeedbackAction.setIcon(icon46)
        self.uifeedbackAction.setIconSize(QtCore.QSize(25, 25))
        self.uifeedbackAction.setObjectName("uifeedbackAction")
        self.verticalLayout_62.addWidget(self.uifeedbackAction)
        self.yijian = QtWidgets.QLabel(self.tab_5)
        self.yijian.setMinimumSize(QtCore.QSize(30, 14))
        self.yijian.setMaximumSize(QtCore.QSize(30, 14))
        self.yijian.setObjectName("yijian")
        self.verticalLayout_62.addWidget(self.yijian)
        self.horizontalLayout_15.addLayout(self.verticalLayout_62)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout_13.addWidget(self.tabWidget)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.verticalLayout_12.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.uiCentralWidget)
        self.label.setMinimumSize(QtCore.QSize(48, 14))
        self.label.setMaximumSize(QtCore.QSize(48, 14))
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.uiBrowseRoutersAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseRoutersAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseRoutersAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseRoutersAction.setToolTip("")
        self.uiBrowseRoutersAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseRoutersAction.setText("")
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(":/classic_icons/router.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBrowseRoutersAction.setIcon(icon47)
        self.uiBrowseRoutersAction.setIconSize(QtCore.QSize(48, 48))
        self.uiBrowseRoutersAction.setObjectName("uiBrowseRoutersAction")
        self.verticalLayout_6.addWidget(self.uiBrowseRoutersAction)
        self.uiBrowseSwitchesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseSwitchesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseSwitchesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseSwitchesAction.setToolTip("")
        self.uiBrowseSwitchesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseSwitchesAction.setText("")
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(":/classic_icons/switch-hover.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBrowseSwitchesAction.setIcon(icon48)
        self.uiBrowseSwitchesAction.setIconSize(QtCore.QSize(48, 48))
        self.uiBrowseSwitchesAction.setObjectName("uiBrowseSwitchesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseSwitchesAction)
        self.uiBrowseSecurityDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseSecurityDevicesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseSecurityDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseSecurityDevicesAction.setToolTip("")
        self.uiBrowseSecurityDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseSecurityDevicesAction.setText("")
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap(":/classic_icons/firewall.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBrowseSecurityDevicesAction.setIcon(icon49)
        self.uiBrowseSecurityDevicesAction.setIconSize(QtCore.QSize(48, 48))
        self.uiBrowseSecurityDevicesAction.setObjectName("uiBrowseSecurityDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseSecurityDevicesAction)
        self.line = QtWidgets.QFrame(self.uiCentralWidget)
        self.line.setMaximumSize(QtCore.QSize(48, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.uiCentralWidget)
        self.label_2.setMinimumSize(QtCore.QSize(48, 0))
        self.label_2.setMaximumSize(QtCore.QSize(48, 14))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.uiBrowseEndDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseEndDevicesAction.setMinimumSize(QtCore.QSize(48, 42))
        self.uiBrowseEndDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseEndDevicesAction.setToolTip("")
        self.uiBrowseEndDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseEndDevicesAction.setText("")
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap(":/classic_icons/pc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBrowseEndDevicesAction.setIcon(icon50)
        self.uiBrowseEndDevicesAction.setIconSize(QtCore.QSize(48, 48))
        self.uiBrowseEndDevicesAction.setObjectName("uiBrowseEndDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseEndDevicesAction)
        self.line_2 = QtWidgets.QFrame(self.uiCentralWidget)
        self.line_2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(self.uiCentralWidget)
        self.label_3.setMinimumSize(QtCore.QSize(48, 14))
        self.label_3.setMaximumSize(QtCore.QSize(48, 14))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.uiBrowseHISDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseHISDevicesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseHISDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseHISDevicesAction.setToolTip("")
        self.uiBrowseHISDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseHISDevicesAction.setText("")
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap(":/images/His.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBrowseHISDevicesAction.setIcon(icon51)
        self.uiBrowseHISDevicesAction.setIconSize(QtCore.QSize(60, 60))
        self.uiBrowseHISDevicesAction.setObjectName("uiBrowseHISDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseHISDevicesAction)
        self.uiBrowseLISDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowseLISDevicesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowseLISDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowseLISDevicesAction.setToolTip("")
        self.uiBrowseLISDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowseLISDevicesAction.setText("")
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap(":/images/Lis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBrowseLISDevicesAction.setIcon(icon52)
        self.uiBrowseLISDevicesAction.setIconSize(QtCore.QSize(60, 60))
        self.uiBrowseLISDevicesAction.setObjectName("uiBrowseLISDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowseLISDevicesAction)
        self.uiBrowsePACSDevicesAction = QtWidgets.QPushButton(self.uiCentralWidget)
        self.uiBrowsePACSDevicesAction.setMinimumSize(QtCore.QSize(48, 48))
        self.uiBrowsePACSDevicesAction.setMaximumSize(QtCore.QSize(48, 48))
        self.uiBrowsePACSDevicesAction.setToolTip("")
        self.uiBrowsePACSDevicesAction.setStyleSheet("QPushButton{\n"
"    border:solid 1px black opacity 0.4;\n"
"    }\n"
"QPushButton:hover {\n"
"    border-width: 1px;\n"
"    background-color:  rgb(240,240,240);\n"
"    border-color: rgb(171,168,165);\n"
"    border-style: outset;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    }")
        self.uiBrowsePACSDevicesAction.setText("")
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap(":/images/Pacs.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBrowsePACSDevicesAction.setIcon(icon53)
        self.uiBrowsePACSDevicesAction.setIconSize(QtCore.QSize(60, 60))
        self.uiBrowsePACSDevicesAction.setObjectName("uiBrowsePACSDevicesAction")
        self.verticalLayout_6.addWidget(self.uiBrowsePACSDevicesAction)
        self.line_3 = QtWidgets.QFrame(self.uiCentralWidget)
        self.line_3.setMaximumSize(QtCore.QSize(48, 16777215))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiNodesDockWidget = QtWidgets.QDockWidget(self.uiCentralWidget)
        self.uiNodesDockWidget.setEnabled(True)
        self.uiNodesDockWidget.setMinimumSize(QtCore.QSize(201, 330))
        self.uiNodesDockWidget.setMaximumSize(QtCore.QSize(201, 524287))
        self.uiNodesDockWidget.setVisible(True)
        self.uiNodesDockWidget.setFloating(False)
        self.uiNodesDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.uiNodesDockWidget.setObjectName("uiNodesDockWidget")
        self.uiNodesDockWidgetContents = QtWidgets.QWidget()
        self.uiNodesDockWidgetContents.setObjectName("uiNodesDockWidgetContents")
        self._2 = QtWidgets.QVBoxLayout(self.uiNodesDockWidgetContents)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setSpacing(0)
        self._2.setObjectName("_2")
        self.uiNodesView = NodesView(self.uiNodesDockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiNodesView.sizePolicy().hasHeightForWidth())
        self.uiNodesView.setSizePolicy(sizePolicy)
        self.uiNodesView.setDragEnabled(False)
        self.uiNodesView.setIconSize(QtCore.QSize(32, 32))
        self.uiNodesView.setRootIsDecorated(False)
        self.uiNodesView.setObjectName("uiNodesView")
        self.uiNodesView.header().setVisible(False)
        self._2.addWidget(self.uiNodesView)
        self.uiNewAppliancePushButton = QtWidgets.QPushButton(self.uiNodesDockWidgetContents)
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap(":/icons/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiNewAppliancePushButton.setIcon(icon54)
        self.uiNewAppliancePushButton.setAutoDefault(False)
        self.uiNewAppliancePushButton.setFlat(True)
        self.uiNewAppliancePushButton.setObjectName("uiNewAppliancePushButton")
        self._2.addWidget(self.uiNewAppliancePushButton)
        self.uiNodesDockWidget.setWidget(self.uiNodesDockWidgetContents)
        self.horizontalLayout.addWidget(self.uiNodesDockWidget)
        self.uiGraphicsView = GraphicsView(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiGraphicsView.sizePolicy().hasHeightForWidth())
        self.uiGraphicsView.setSizePolicy(sizePolicy)
        self.uiGraphicsView.setObjectName("uiGraphicsView")
        self.horizontalLayout.addWidget(self.uiGraphicsView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.uiTopologySummaryDockWidget = QtWidgets.QDockWidget(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTopologySummaryDockWidget.sizePolicy().hasHeightForWidth())
        self.uiTopologySummaryDockWidget.setSizePolicy(sizePolicy)
        self.uiTopologySummaryDockWidget.setMinimumSize(QtCore.QSize(256, 160))
        self.uiTopologySummaryDockWidget.setMaximumSize(QtCore.QSize(256, 524287))
        self.uiTopologySummaryDockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.uiTopologySummaryDockWidget.setObjectName("uiTopologySummaryDockWidget")
        self.uiTopologySummaryDockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTopologySummaryDockWidgetContents.sizePolicy().hasHeightForWidth())
        self.uiTopologySummaryDockWidgetContents.setSizePolicy(sizePolicy)
        self.uiTopologySummaryDockWidgetContents.setObjectName("uiTopologySummaryDockWidgetContents")
        self._3 = QtWidgets.QGridLayout(self.uiTopologySummaryDockWidgetContents)
        self._3.setContentsMargins(0, 0, 0, 0)
        self._3.setSpacing(0)
        self._3.setObjectName("_3")
        self.uiTopologySummaryTreeWidget = TopologySummaryView(self.uiTopologySummaryDockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTopologySummaryTreeWidget.sizePolicy().hasHeightForWidth())
        self.uiTopologySummaryTreeWidget.setSizePolicy(sizePolicy)
        self.uiTopologySummaryTreeWidget.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.uiTopologySummaryTreeWidget.setObjectName("uiTopologySummaryTreeWidget")
        self.uiTopologySummaryTreeWidget.header().setVisible(False)
        self._3.addWidget(self.uiTopologySummaryTreeWidget, 0, 0, 1, 1)
        self.uiTopologySummaryDockWidget.setWidget(self.uiTopologySummaryDockWidgetContents)
        self.verticalLayout.addWidget(self.uiTopologySummaryDockWidget)
        self.uiServerSummaryDockWidget = QtWidgets.QDockWidget(self.uiCentralWidget)
        self.uiServerSummaryDockWidget.setMinimumSize(QtCore.QSize(256, 160))
        self.uiServerSummaryDockWidget.setMaximumSize(QtCore.QSize(256, 524287))
        self.uiServerSummaryDockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.uiServerSummaryDockWidget.setObjectName("uiServerSummaryDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.uiServerSummaryTreeWidget = ServerSummaryView(self.dockWidgetContents)
        self.uiServerSummaryTreeWidget.setMaximumSize(QtCore.QSize(256, 16777215))
        self.uiServerSummaryTreeWidget.setObjectName("uiServerSummaryTreeWidget")
        self.uiServerSummaryTreeWidget.headerItem().setText(0, "1")
        self.uiServerSummaryTreeWidget.header().setVisible(False)
        self.gridLayout.addWidget(self.uiServerSummaryTreeWidget, 0, 0, 1, 1)
        self.uiServerSummaryDockWidget.setWidget(self.dockWidgetContents)
        self.verticalLayout.addWidget(self.uiServerSummaryDockWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.uiConsoleDockWidget = QtWidgets.QDockWidget(self.uiCentralWidget)
        self.uiConsoleDockWidget.setMinimumSize(QtCore.QSize(90, 130))
        self.uiConsoleDockWidget.setMaximumSize(QtCore.QSize(524287, 134))
        self.uiConsoleDockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.uiConsoleDockWidget.setObjectName("uiConsoleDockWidget")
        self.uiConsoleDockWidgetContents = QtWidgets.QWidget()
        self.uiConsoleDockWidgetContents.setObjectName("uiConsoleDockWidgetContents")
        self._4 = QtWidgets.QVBoxLayout(self.uiConsoleDockWidgetContents)
        self._4.setContentsMargins(0, 0, 0, 0)
        self._4.setSpacing(0)
        self._4.setObjectName("_4")
        self.uiConsoleTextEdit = ConsoleView(self.uiConsoleDockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiConsoleTextEdit.sizePolicy().hasHeightForWidth())
        self.uiConsoleTextEdit.setSizePolicy(sizePolicy)
        self.uiConsoleTextEdit.setObjectName("uiConsoleTextEdit")
        self._4.addWidget(self.uiConsoleTextEdit)
        self.uiConsoleDockWidget.setWidget(self.uiConsoleDockWidgetContents)
        self.verticalLayout_2.addWidget(self.uiConsoleDockWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.uiCentralWidget)
        self.uiStatusBar = QtWidgets.QStatusBar(MainWindow)
        self.uiStatusBar.setObjectName("uiStatusBar")
        self.pushButton = QtWidgets.QPushButton()
        self.pushButton.setText("用户名")
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/MNSS.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.tabWidget.setCornerWidget(self.pushButton)
        MainWindow.setStatusBar(self.uiStatusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">MNSS</span></p></body></html>"))
        self.uiNewProjectAction.setStatusTip(_translate("MainWindow", "新建工程"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">新建</p></body></html>"))
        self.uiOpenProjectAction.setStatusTip(_translate("MainWindow", "打开工程"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">打开</p></body></html>"))
        self.uiSaveProjectAction.setStatusTip(_translate("MainWindow", "保存工程"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">保存</p></body></html>"))
        self.uiSaveProjectAsAction.setStatusTip(_translate("MainWindow", "工程另存为"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">另存</p></body></html>"))
        self.uiImportProjectAction.setStatusTip(_translate("MainWindow", "导入设备"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">导入</p></body></html>"))
        self.uiExportProjectAction.setStatusTip(_translate("MainWindow", "导出设备"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">导出</p></body></html>"))
        self.pushButton_28.setStatusTip(_translate("MainWindow", "上传工程"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">上传</p></body></html>"))
        self.pushButton_30.setStatusTip(_translate("MainWindow", "下载医院信息系统"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">下载</p></body></html>"))
        self.uiQuitAction.setStatusTip(_translate("MainWindow", "退出程序"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">退出</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "文件"))
        self.uiPreferencesAction.setStatusTip(_translate("MainWindow", "总设置"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">通用</p></body></html>"))
        self.pushButton_5.setStatusTip(_translate("MainWindow", "显示服务器相关设置"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">服务器</p></body></html>"))
        self.pushButton_49.setStatusTip(_translate("MainWindow", "显示抓包相关设置"))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">抓包</p></body></html>"))
        self.pushButton_7.setStatusTip(_translate("MainWindow", "显示VPCS相关设置"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">VPCS</p></body></html>"))
        self.uiDynamipsAction.setStatusTip(_translate("MainWindow", "显示Dynamips设置"))
        self.label_60.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">模拟器</p></body></html>"))
        self.uifUnixAction.setStatusTip(_translate("MainWindow", "显示IOS on UNIX设置"))
        self.label_59.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Unix</p></body></html>"))
        self.uiVMAction.setStatusTip(_translate("MainWindow", "显示VMware设置"))
        self.label_57.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">VM</p></body></html>"))
        self.pushButton_6.setStatusTip(_translate("MainWindow", "显示路由器相关设置"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">路由器</p></body></html>"))
        self.UiIOUAction.setStatusTip(_translate("MainWindow", "显示IOU设置"))
        self.label_61.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">IOU</p></body></html>"))
        self.pushButton_8.setStatusTip(_translate("MainWindow", "显示医院信息系统相关设置"))
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">医用</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "设置"))
        self.uiStartAllAction.setStatusTip(_translate("MainWindow", "运行设备"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">运行</p></body></html>"))
        self.uiSuspendAllAction.setStatusTip(_translate("MainWindow", "暂停设备"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">暂停</p></body></html>"))
        self.uiStopAllAction.setStatusTip(_translate("MainWindow", "终止设备"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">终止</p></body></html>"))
        self.uiReloadAllAction.setStatusTip(_translate("MainWindow", "重启设备"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">重启</p></body></html>"))
        self.uiAddLinkAction.setStatusTip(_translate("MainWindow", "添加连接线"))
        self.label_58.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">连接</p></body></html>"))
        self.uiShowPortNamesAction.setStatusTip(_translate("MainWindow", "显示接口号"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">接口</p></body></html>"))
        self.uiConsoleAllAction.setStatusTip(_translate("MainWindow", "配置设备"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">配置</p></body></html>"))
        self.uiZoomInAction.setStatusTip(_translate("MainWindow", "放大视图"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">放大</p></body></html>"))
        self.uiZoomOutAction.setStatusTip(_translate("MainWindow", "缩小视图"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">缩小</p></body></html>"))
        self.uiScreenshotAction.setStatusTip(_translate("MainWindow", "屏幕截取"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">截屏</p></body></html>"))
        self.uiShowLayersAction.setStatusTip(_translate("MainWindow", "显示层次"))
        self.uiShowLayersAction.setText(_translate("MainWindow", "层次"))
        self.uiShowGridAction.setStatusTip(_translate("MainWindow", "显示网格"))
        self.uiShowGridAction.setText(_translate("MainWindow", "网格"))
        self.uiSnapToGridAction.setStatusTip(_translate("MainWindow", "对齐网格"))
        self.uiSnapToGridAction.setText(_translate("MainWindow", "对齐网格"))
        self.uiInsertImageAction.setStatusTip(_translate("MainWindow", "插入图片"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">图片</p></body></html>"))
        self.uiAddNoteAction.setStatusTip(_translate("MainWindow", "添加标签"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">标签</p></body></html>"))
        self.uiDrawEllipseAction.setStatusTip(_translate("MainWindow", "添加圆形"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">圆形</p></body></html>"))
        self.uiDrawRectangleAction.setStatusTip(_translate("MainWindow", "添加矩形"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">矩形</p></body></html>"))
        self.uiShowTopology.setText(_translate("MainWindow", "拓扑汇总   "))
        self.uiShowServer.setText(_translate("MainWindow", "服务器状态 "))
        self.uiShowConsole.setText(_translate("MainWindow", "控制台     "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "工作台"))
        self.pushButton_50.setStatusTip(_translate("MainWindow", "显示安全教程"))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">安全</p></body></html>"))
        self.pushButton_51.setStatusTip(_translate("MainWindow", "显示医用教程"))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">医用</p></body></html>"))
        self.pushButton_47.setStatusTip(_translate("MainWindow", "显示网络教程"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">网络</p></body></html>"))
        self.pushButton_52.setStatusTip(_translate("MainWindow", "显示拓扑案例"))
        self.label_52.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">案例</p></body></html>"))
        self.pushButton_53.setStatusTip(_translate("MainWindow", "医用系统安装向导"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">向导</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "教程"))
        self.uiCheckForUpdateAction.setStatusTip(_translate("MainWindow", "更新软件"))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">更新</p></body></html>"))
        self.uiOnlineHelpAction.setStatusTip(_translate("MainWindow", "显示官网"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">官网</p></body></html>"))
        self.uiExportDebugInformationAction.setStatusTip(_translate("MainWindow", "输出DeBug信息"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">DeBug</p></body></html>"))
        self.uiDoctorAction.setStatusTip(_translate("MainWindow", "显示诊断信息"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">诊断</p></body></html>"))
        self.uiAboutAction.setStatusTip(_translate("MainWindow", "关于我们"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">关于</p></body></html>"))
        self.uifeedbackAction.setStatusTip(_translate("MainWindow", "关于我们"))
        self.yijian.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">反馈</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "帮助"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">网络设备</p></body></html>"))
        self.uiBrowseRoutersAction.setStatusTip(_translate("MainWindow", " 添加路由器"))
        self.uiBrowseSwitchesAction.setStatusTip(_translate("MainWindow", "添加交换机"))
        self.uiBrowseSecurityDevicesAction.setStatusTip(_translate("MainWindow", "添加安全设备"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">终端设备</p></body></html>"))
        self.uiBrowseEndDevicesAction.setStatusTip(_translate("MainWindow", "添加终端设备"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">信息系统</p></body></html>"))
        self.uiBrowseHISDevicesAction.setStatusTip(_translate("MainWindow", "添加HIS系统"))
        self.uiBrowseLISDevicesAction.setStatusTip(_translate("MainWindow", "添加LIS系统"))
        self.uiBrowsePACSDevicesAction.setStatusTip(_translate("MainWindow", "添加PACS系统"))
        self.uiNodesDockWidget.setWindowTitle(_translate("MainWindow", "节点类型"))
        self.uiNodesView.setToolTip(_translate("MainWindow", "Drag a node to the workspace (Press SHIFT while dragging to add multiple identical nodes)."))
        self.uiNodesView.headerItem().setText(0, _translate("MainWindow", "1"))
        self.uiNewAppliancePushButton.setText(_translate("MainWindow", "添加新的设备"))
        self.uiTopologySummaryDockWidget.setWindowTitle(_translate("MainWindow", "拓扑汇总"))
        self.uiTopologySummaryTreeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        self.uiServerSummaryDockWidget.setWindowTitle(_translate("MainWindow", "服务器状态"))
        self.uiConsoleDockWidget.setWindowTitle(_translate("MainWindow", "控制台"))

from ..console_view import ConsoleView
from ..graphics_view import GraphicsView
from ..nodes_view import NodesView
from ..server_summary_view import ServerSummaryView
from ..topology_summary_view import TopologySummaryView
import resources_rc
